//! Generated by orbweaver-gen from the registry.
//!
//! Names and order only; every marshalling decision is a call into
//! `orbweaver_gen::rt`, so the wire knowledge exists once.
//!
//! Each interface yields a client stub, a servant trait and a
//! skeleton that adapts the trait to `orbweaver_gen::rt::Dispatch`.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![forbid(unsafe_code)]
#![deny(missing_docs)]
#![allow(non_camel_case_types, non_snake_case, dead_code)]

/// IDL module `gc24`.
pub mod gc24 {
    use orbweaver_gen::rt::{self, Cdr};
    /// IDL exception `IDL:gc24/Busy:1.0`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct Busy {
    }
    impl Cdr for Busy {
        fn put(&self, _e: &mut rt::Encoder) -> Result<(), rt::GiopError> {
            Ok(())
        }
        fn get(_d: &mut rt::Decoder<'_>) -> Result<Self, rt::GiopError> {
            Ok(Self {
            })
        }
    }

    /// A gauge whose skeleton exercises oneway, attributes and alignment
    ///
    /// Client stub for `IDL:gc24/Gauge:1.0`.
    ///
    /// Static twin of the dynamic path; §8 requires their bytes to be
    /// identical, and the harness holds them to it.
    ///
    /// Generic over the invoker on purpose (PLAN §7.4 I1): over a raw
    /// `Connection` inside the trust boundary, or over the guarded
    /// wrapper at it — a stub hard-wired to the transport would be the
    /// §4.7 bypass in compiled form.
    pub struct GaugeClient<C: rt::Invoker> {
        /// What calls travel over.
        pub conn: C,
    }
    impl<C: rt::Invoker> GaugeClient<C> {
        /// A stub over an open invoker.
        pub fn new(conn: C) -> Self { Self { conn } }
        /// Records one sample and returns the reading it produced
        ///
        /// `record` on the wire.
        pub fn record(&mut self, sample: f64, unit: String) -> Result<crate::emitted::f_24_skeleton_surface::gc24::Reading, rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            sample.put(&mut __probe)?;
            unit.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("record", |__e| {
                let _ = sample.put(__e);
                let _ = unit.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// whether it happened, so the scope is all that guards it
        ///
        /// `reset` on the wire.
        pub fn reset(&mut self) -> Result<(), rt::GiopError> {
            self.conn.invoke_oneway("reset", |__e| {
            })
        }
        /// Multiplies every stored sample and answers how many changed
        ///
        /// `scale_all` on the wire.
        pub fn scale_all(&mut self, e: f64) -> Result<i32, rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            e.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("scale_all", |__e| {
                let _ = e.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// Splits the latest reading into its parts
        ///
        /// `split` on the wire.
        pub fn split(&mut self) -> Result<(f64, String), rt::GiopError> {
            let __reply = self.conn.invoke("split", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            let __r1 = Cdr::get(&mut __body)?;
            Ok((__r0, __r1))
        }
        /// Human-readable label for this gauge
        ///
        /// `_get_label` on the wire.
        pub fn label(&mut self) -> Result<String, rt::GiopError> {
            let __reply = self.conn.invoke("_get_label", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// Human-readable label for this gauge
        ///
        /// `_set_label` on the wire.
        pub fn set_label(&mut self, value: String) -> Result<(), rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            value.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("_set_label", |__e| {
                let _ = value.put(__e);
            })?;
            let _ = __reply;
            Ok(())
        }
        /// The most recent reading, or a zeroed one before any sample
        ///
        /// `_get_latest` on the wire.
        pub fn latest(&mut self) -> Result<crate::emitted::f_24_skeleton_surface::gc24::Reading, rt::GiopError> {
            let __reply = self.conn.invoke("_get_latest", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
    }
    
    /// Everything a servant for `IDL:gc24/Gauge:1.0` can fail with.
    ///
    /// `System` is always here, whatever the contract declares: an unknown
    /// key is `OBJECT_NOT_EXIST`, a refused call is `NO_PERMISSION`, a
    /// temporary refusal is `TRANSIENT`, and IDL has no way to declare any
    /// of them. Build one with `rt::raise::*`, which does not produce a
    /// `SystemException` until the completion status is stated — the field
    /// that tells the caller whether a retry is safe, and the one thing a
    /// generator cannot know for a servant.
    ///
    /// The remaining variants are the exceptions named in a `raises`
    /// clause of this interface or of one it inherits. `write` puts the
    /// body §9.4.3.1 describes — repository id first, then the members —
    /// which is exactly what the client side reads back out of
    /// `rt::GiopError::UserException`.
    #[derive(Debug, Clone)]
    pub enum GaugeFault {
        /// A CORBA system exception, with the completion status the
        /// servant chose. Travels as a `SystemException` reply.
        System(rt::SystemException),
        /// IDL exception `IDL:gc24/Busy:1.0`.
        Busy(crate::emitted::f_24_skeleton_surface::gc24::Busy),
        /// IDL exception `IDL:gc24/Rejected:1.0`.
        Rejected(crate::emitted::f_24_skeleton_surface::gc24::Rejected),
    }
    impl From<rt::SystemException> for GaugeFault {
        fn from(__ex: rt::SystemException) -> Self {
            Self::System(__ex)
        }
    }
    impl PartialEq for GaugeFault {
        fn eq(&self, __other: &Self) -> bool {
            match (self, __other) {
                (Self::System(__a), Self::System(__b)) => {
                    __a.id == __b.id
                        && __a.minor == __b.minor
                        && __a.completed == __b.completed
                }
                (Self::Busy(__a), Self::Busy(__b)) => __a == __b,
                (Self::Rejected(__a), Self::Rejected(__b)) => __a == __b,
                _ => false,
            }
        }
    }
    impl GaugeFault {
        /// The repository id of the user exception this fault carries, or
        /// `None` for a system exception, which carries its own.
        pub fn user_id(&self) -> Option<&'static str> {
            match self {
                Self::System(_) => None,
                Self::Busy(_) => Some("IDL:gc24/Busy:1.0"),
                Self::Rejected(_) => Some("IDL:gc24/Rejected:1.0"),
            }
        }
        /// Writes this fault into the reply body and says which reply status the
        /// bytes travel under.
        ///
        /// A system exception writes nothing and comes back as `Err`: it is not a
        /// body under a status, it *replaces* the reply (§9.4.3.1), so the
        /// dispatcher hands it to the server to encode instead. That is also why
        /// nothing may be written before the fault is known — the whole buffer
        /// travels under one status.
        pub fn write(&self, __out: &mut rt::Encoder) -> Result<rt::DispatchBody, rt::SystemException> {
            match self {
                Self::System(__ex) => Err(__ex.clone()),
                Self::Busy(__v) => {
                    __out.put_str("IDL:gc24/Busy:1.0");
                    __v.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::UserException)
                }
                Self::Rejected(__v) => {
                    __out.put_str("IDL:gc24/Rejected:1.0");
                    __v.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::UserException)
                }
            }
        }
    }
    /// A gauge whose skeleton exercises oneway, attributes and alignment
    ///
    /// What a servant for `IDL:gc24/Gauge:1.0` must implement.
    ///
    /// One method per operation and per attribute accessor, taking decoded
    /// Rust arguments. Nothing here mentions GIOP: the wire is entirely the
    /// business of `GaugeSkeleton`, which adapts this trait to
    /// `rt::Dispatch`.
    ///
    /// Every method may fail with a `GaugeFault`: a declared user exception,
    /// or a system exception built with `rt::raise::*` — the vocabulary
    /// (`OBJECT_NOT_EXIST`, `NO_PERMISSION`, `BAD_PARAM`, `TRANSIENT`) that
    /// no contract declares and every servant needs.
    pub trait GaugeServant {
        /// Records one sample and returns the reading it produced
        ///
        /// `record` on the wire.
        fn record(&mut self, sample: f64, unit: String) -> Result<crate::emitted::f_24_skeleton_surface::gc24::Reading, GaugeFault>;
        /// whether it happened, so the scope is all that guards it
        ///
        /// `reset` on the wire.
        ///
        /// `oneway`: the caller is not waiting, so neither a result nor a fault
        /// can reach it. Returning `Err` here is dropped — deliberately, and
        /// logged, because a oneway that fails invisibly is undebuggable.
        fn reset(&mut self) -> Result<(), GaugeFault>;
        /// Multiplies every stored sample and answers how many changed
        ///
        /// `scale_all` on the wire.
        fn scale_all(&mut self, e: f64) -> Result<i32, GaugeFault>;
        /// Splits the latest reading into its parts
        ///
        /// `split` on the wire.
        fn split(&mut self) -> Result<(f64, String), GaugeFault>;
        /// Human-readable label for this gauge
        ///
        /// `_get_label` on the wire.
        fn label(&mut self) -> Result<String, GaugeFault>;
        /// Human-readable label for this gauge
        ///
        /// `_set_label` on the wire.
        fn set_label(&mut self, value: String) -> Result<(), GaugeFault>;
        /// The most recent reading, or a zeroed one before any sample
        ///
        /// `_get_latest` on the wire.
        fn latest(&mut self) -> Result<crate::emitted::f_24_skeleton_surface::gc24::Reading, GaugeFault>;
    }
    /// Serves `IDL:gc24/Gauge:1.0`: decodes the request, calls the servant, encodes the reply.
    ///
    /// Hand it to `rt::Server::serve` in place of a hand-written
    /// `rt::Dispatch`. What it answers, beyond the contract's own
    /// operations:
    ///
    /// * `_is_a`, from the inheritance chain the registry resolved, because
    ///   an ORB probes with it before it will narrow;
    /// * `_non_existent`, with `false`;
    /// * every other name with `BAD_OPERATION`, including the `_set_` of a
    ///   readonly attribute;
    /// * a body that does not decode with `MARSHAL`.
    ///
    /// A `GaugeFault::System` the servant raises is passed through
    /// unchanged — repository id, minor code and completion status — so the
    /// servant's answer about whether a retry is safe is the one the client
    /// receives.
    pub struct GaugeSkeleton<S: GaugeServant> {
        /// The implementation invocations are delivered to.
        pub servant: S,
    }
    impl<S: GaugeServant> GaugeSkeleton<S> {
        /// A skeleton over a servant.
        pub fn new(servant: S) -> Self { Self { servant } }
    }
    impl<S: GaugeServant> rt::Dispatch for GaugeSkeleton<S> {
        fn dispatch_body(
            &mut self,
            __req: &rt::Request,
            __out: &mut rt::Encoder,
        ) -> Result<rt::DispatchBody, rt::SystemException> {
            let mut __args = __req.body().map_err(|_| rt::SystemException::marshal())?;
            match __req.operation.as_str() {
                "record" => {
                    let sample: f64 = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    let unit: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.record(sample, unit) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "reset" => {
                    // oneway (§9.4.1): no reply may be written, at all. An empty one
                    // is a whole extra message, which the peer — not waiting for it —
                    // would read as the header of the next reply. The servant's
                    // verdict has no way back, so it is dropped — and logged, so the
                    // drop is a decision somebody can see rather than a silence.
                    if let Err(__f) = self.servant.reset() {
                        rt::oneway_fault_dropped("IDL:gc24/Gauge:1.0", "reset", &__f);
                    }
                    Ok(rt::DispatchBody::Return)
                }
                "scale_all" => {
                    let e: f64 = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.scale_all(e) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "split" => {
                    match self.servant.split() {
                        Ok((__r0, __r1)) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            __r1.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_get_label" => {
                    match self.servant.label() {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_set_label" => {
                    let value: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.set_label(value) {
                        Ok(()) => {
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_get_latest" => {
                    match self.servant.latest() {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_is_a" => {
                    let __id: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    let __answer = matches!(__id.as_str(),
                        "IDL:gc24/Gauge:1.0" |
                        rt::OBJECT_ID);
                    __answer.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::Return)
                }
                "_non_existent" => {
                    false.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::Return)
                }
                _ => Err(rt::SystemException::bad_operation()),
            }
        }
        fn dispatch(
            &mut self,
            __req: &rt::Request,
            __out: &mut rt::Encoder,
        ) -> Result<(), rt::SystemException> {
            match self.dispatch_body(__req, __out)? {
                rt::DispatchBody::Return => Ok(()),
                rt::DispatchBody::UserException => {
                    Err(rt::SystemException::unknown_user_exception())
                }
            }
        }
    }

    /// IDL struct `IDL:gc24/Reading:1.0`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct Reading {
        /// IDL member `at`, marshalled first.
        pub at: f64,
        /// IDL member `sequence_no`, marshalled second.
        pub sequence_no: i32,
        /// IDL member `unit`, marshalled third.
        pub unit: String,
    }
    impl Cdr for Reading {
        fn put(&self, e: &mut rt::Encoder) -> Result<(), rt::GiopError> {
            self.at.put(e)?;
            self.sequence_no.put(e)?;
            self.unit.put(e)?;
            Ok(())
        }
        fn get(d: &mut rt::Decoder<'_>) -> Result<Self, rt::GiopError> {
            Ok(Self {
                at: Cdr::get(d)?,
                sequence_no: Cdr::get(d)?,
                unit: Cdr::get(d)?,
            })
        }
    }

    /// IDL exception `IDL:gc24/Rejected:1.0`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct Rejected {
        /// IDL member `why`, marshalled first.
        pub why: String,
        /// IDL member `code`, marshalled second.
        pub code: i32,
    }
    impl Cdr for Rejected {
        fn put(&self, e: &mut rt::Encoder) -> Result<(), rt::GiopError> {
            self.why.put(e)?;
            self.code.put(e)?;
            Ok(())
        }
        fn get(d: &mut rt::Decoder<'_>) -> Result<Self, rt::GiopError> {
            Ok(Self {
                why: Cdr::get(d)?,
                code: Cdr::get(d)?,
            })
        }
    }

}
