//! Generated by orbweaver-gen from the registry.
//!
//! Names and order only; every marshalling decision is a call into
//! `orbweaver_gen::rt`, so the wire knowledge exists once.
//!
//! Each interface yields a client stub, a servant trait and a
//! skeleton that adapts the trait to `orbweaver_gen::rt::Dispatch`.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![forbid(unsafe_code)]
#![deny(missing_docs)]
#![allow(non_camel_case_types, non_snake_case, dead_code)]

/// IDL module `fault25`.
pub mod fault25 {
    use orbweaver_gen::rt::{self, Cdr};
    /// A key-value vault whose every failure is a system exception
    ///
    /// Client stub for `IDL:fault25/Vault:1.0`.
    ///
    /// Static twin of the dynamic path; §8 requires their bytes to be
    /// identical, and the harness holds them to it.
    ///
    /// Generic over the invoker on purpose (PLAN §7.4 I1): over a raw
    /// `Connection` inside the trust boundary, or over the guarded
    /// wrapper at it — a stub hard-wired to the transport would be the
    /// §4.7 bypass in compiled form.
    pub struct VaultClient<C: rt::Invoker> {
        /// What calls travel over.
        pub conn: C,
    }
    impl<C: rt::Invoker> VaultClient<C> {
        /// A stub over an open invoker.
        pub fn new(conn: C) -> Self { Self { conn } }
        /// Reads one entry; an absent key is OBJECT_NOT_EXIST
        ///
        /// `fetch` on the wire.
        pub fn fetch(&mut self, key: String) -> Result<String, rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            key.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("fetch", |__e| {
                let _ = key.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// Fires and forgets; a fault here has no reply to travel in
        ///
        /// `forget` on the wire.
        pub fn forget(&mut self, key: String) -> Result<(), rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            key.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            self.conn.invoke_oneway("forget", |__e| {
                let _ = key.put(__e);
            })
        }
        /// Rotates to the next generation; refuses mid-rotation with TRANSIENT
        ///
        /// `rotate` on the wire.
        pub fn rotate(&mut self, wanted: i32) -> Result<i32, rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            wanted.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("rotate", |__e| {
                let _ = wanted.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// Writes one entry; refused callers get NO_PERMISSION, an empty key BAD_PARAM
        ///
        /// `store` on the wire.
        pub fn store(&mut self, key: String, text: String) -> Result<(), rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            key.put(&mut __probe)?;
            text.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("store", |__e| {
                let _ = key.put(__e);
                let _ = text.put(__e);
            })?;
            let _ = __reply;
            Ok(())
        }
        /// How many entries the vault holds
        ///
        /// `_get_depth` on the wire.
        pub fn depth(&mut self) -> Result<i32, rt::GiopError> {
            let __reply = self.conn.invoke("_get_depth", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
    }
    
    /// Everything a servant for `IDL:fault25/Vault:1.0` can fail with.
    ///
    /// `System` is always here, whatever the contract declares: an unknown
    /// key is `OBJECT_NOT_EXIST`, a refused call is `NO_PERMISSION`, a
    /// temporary refusal is `TRANSIENT`, and IDL has no way to declare any
    /// of them. Build one with `rt::raise::*`, which does not produce a
    /// `SystemException` until the completion status is stated — the field
    /// that tells the caller whether a retry is safe, and the one thing a
    /// generator cannot know for a servant.
    ///
    /// This interface names no `raises` clause, so `System` is the only
    /// variant. It is still an inhabited type: a servant that cannot fail
    /// is not a servant anybody can write.
    #[derive(Debug, Clone)]
    pub enum VaultFault {
        /// A CORBA system exception, with the completion status the
        /// servant chose. Travels as a `SystemException` reply.
        System(rt::SystemException),
    }
    impl From<rt::SystemException> for VaultFault {
        fn from(__ex: rt::SystemException) -> Self {
            Self::System(__ex)
        }
    }
    impl PartialEq for VaultFault {
        fn eq(&self, __other: &Self) -> bool {
            match (self, __other) {
                (Self::System(__a), Self::System(__b)) => {
                    __a.id == __b.id
                        && __a.minor == __b.minor
                        && __a.completed == __b.completed
                }
            }
        }
    }
    impl VaultFault {
        /// The repository id of the user exception this fault carries, or
        /// `None` for a system exception, which carries its own.
        pub fn user_id(&self) -> Option<&'static str> {
            match self {
                Self::System(_) => None,
            }
        }
        /// Writes this fault into the reply body and says which reply status the
        /// bytes travel under.
        ///
        /// A system exception writes nothing and comes back as `Err`: it is not a
        /// body under a status, it *replaces* the reply (§9.4.3.1), so the
        /// dispatcher hands it to the server to encode instead. That is also why
        /// nothing may be written before the fault is known — the whole buffer
        /// travels under one status.
        pub fn write(&self, __out: &mut rt::Encoder) -> Result<rt::DispatchBody, rt::SystemException> {
            let _ = __out;
            match self {
                Self::System(__ex) => Err(__ex.clone()),
            }
        }
    }
    /// A key-value vault whose every failure is a system exception
    ///
    /// What a servant for `IDL:fault25/Vault:1.0` must implement.
    ///
    /// One method per operation and per attribute accessor, taking decoded
    /// Rust arguments. Nothing here mentions GIOP: the wire is entirely the
    /// business of `VaultSkeleton`, which adapts this trait to
    /// `rt::Dispatch`.
    ///
    /// Every method may fail with a `VaultFault`: a declared user exception,
    /// or a system exception built with `rt::raise::*` — the vocabulary
    /// (`OBJECT_NOT_EXIST`, `NO_PERMISSION`, `BAD_PARAM`, `TRANSIENT`) that
    /// no contract declares and every servant needs.
    pub trait VaultServant {
        /// Reads one entry; an absent key is OBJECT_NOT_EXIST
        ///
        /// `fetch` on the wire.
        fn fetch(&mut self, key: String) -> Result<String, VaultFault>;
        /// Fires and forgets; a fault here has no reply to travel in
        ///
        /// `forget` on the wire.
        ///
        /// `oneway`: the caller is not waiting, so neither a result nor a fault
        /// can reach it. Returning `Err` here is dropped — deliberately, and
        /// logged, because a oneway that fails invisibly is undebuggable.
        fn forget(&mut self, key: String) -> Result<(), VaultFault>;
        /// Rotates to the next generation; refuses mid-rotation with TRANSIENT
        ///
        /// `rotate` on the wire.
        fn rotate(&mut self, wanted: i32) -> Result<i32, VaultFault>;
        /// Writes one entry; refused callers get NO_PERMISSION, an empty key BAD_PARAM
        ///
        /// `store` on the wire.
        fn store(&mut self, key: String, text: String) -> Result<(), VaultFault>;
        /// How many entries the vault holds
        ///
        /// `_get_depth` on the wire.
        fn depth(&mut self) -> Result<i32, VaultFault>;
    }
    /// Serves `IDL:fault25/Vault:1.0`: decodes the request, calls the servant, encodes the reply.
    ///
    /// Hand it to `rt::Server::serve` in place of a hand-written
    /// `rt::Dispatch`. What it answers, beyond the contract's own
    /// operations:
    ///
    /// * `_is_a`, from the inheritance chain the registry resolved, because
    ///   an ORB probes with it before it will narrow;
    /// * `_non_existent`, with `false`;
    /// * every other name with `BAD_OPERATION`, including the `_set_` of a
    ///   readonly attribute;
    /// * a body that does not decode with `MARSHAL`.
    ///
    /// A `VaultFault::System` the servant raises is passed through
    /// unchanged — repository id, minor code and completion status — so the
    /// servant's answer about whether a retry is safe is the one the client
    /// receives.
    pub struct VaultSkeleton<S: VaultServant> {
        /// The implementation invocations are delivered to.
        pub servant: S,
    }
    impl<S: VaultServant> VaultSkeleton<S> {
        /// A skeleton over a servant.
        pub fn new(servant: S) -> Self { Self { servant } }
    }
    impl<S: VaultServant> rt::Dispatch for VaultSkeleton<S> {
        fn dispatch_body(
            &mut self,
            __req: &rt::Request,
            __out: &mut rt::Encoder,
        ) -> Result<rt::DispatchBody, rt::SystemException> {
            let mut __args = __req.body().map_err(|_| rt::SystemException::marshal())?;
            match __req.operation.as_str() {
                "fetch" => {
                    let key: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.fetch(key) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "forget" => {
                    let key: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    // oneway (§9.4.1): no reply may be written, at all. An empty one
                    // is a whole extra message, which the peer — not waiting for it —
                    // would read as the header of the next reply. The servant's
                    // verdict has no way back, so it is dropped — and logged, so the
                    // drop is a decision somebody can see rather than a silence.
                    if let Err(__f) = self.servant.forget(key) {
                        rt::oneway_fault_dropped("IDL:fault25/Vault:1.0", "forget", &__f);
                    }
                    Ok(rt::DispatchBody::Return)
                }
                "rotate" => {
                    let wanted: i32 = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.rotate(wanted) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "store" => {
                    let key: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    let text: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.store(key, text) {
                        Ok(()) => {
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_get_depth" => {
                    match self.servant.depth() {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_is_a" => {
                    let __id: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    let __answer = matches!(__id.as_str(),
                        "IDL:fault25/Vault:1.0" |
                        rt::OBJECT_ID);
                    __answer.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::Return)
                }
                "_non_existent" => {
                    false.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::Return)
                }
                _ => Err(rt::SystemException::bad_operation()),
            }
        }
        fn dispatch(
            &mut self,
            __req: &rt::Request,
            __out: &mut rt::Encoder,
        ) -> Result<(), rt::SystemException> {
            match self.dispatch_body(__req, __out)? {
                rt::DispatchBody::Return => Ok(()),
                rt::DispatchBody::UserException => {
                    Err(rt::SystemException::unknown_user_exception())
                }
            }
        }
    }

}
