//! Generated by orbweaver-gen from the registry.
//!
//! Names and order only; every marshalling decision is a call into
//! `orbweaver_gen::rt`, so the wire knowledge exists once.
//!
//! Each interface yields a client stub, a servant trait and a
//! skeleton that adapts the trait to `orbweaver_gen::rt::Dispatch`.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![forbid(unsafe_code)]
#![deny(missing_docs)]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]
#![allow(clippy::wrong_self_convention, clippy::should_implement_trait, clippy::len_without_is_empty, clippy::too_many_arguments)]

/// IDL module `gc27`.
pub mod gc27 {
    use orbweaver_gen::rt::{self, Cdr};
    /// IDL typedef `IDL:gc27/Blob:1.0`.
    pub type Blob = orbweaver_gen::rt::Bounded<Vec<u8>, 6>;

    /// IDL typedef `IDL:gc27/BlobSeq:1.0`.
    pub type BlobSeq = Vec<crate::emitted::f_27_bounds::gc27::Blob>;

    /// Client stub for `IDL:gc27/Ledger:1.0`.
    ///
    /// Static twin of the dynamic path; §8 requires their bytes to be
    /// identical, and the harness holds them to it.
    ///
    /// Generic over the invoker on purpose (PLAN §7.4 I1): over a raw
    /// `Connection` inside the trust boundary, or over the guarded
    /// wrapper at it — a stub hard-wired to the transport would be the
    /// §4.7 bypass in compiled form.
    pub struct LedgerClient<C: rt::Invoker> {
        /// What calls travel over.
        pub conn: C,
    }
    impl<C: rt::Invoker> LedgerClient<C> {
        /// A stub over an open invoker.
        pub fn new(conn: C) -> Self { Self { conn } }
        /// `digest`. The contract carries no `ai_desc` for this operation.
        pub fn digest(&mut self, batch: crate::emitted::f_27_bounds::gc27::BlobSeq) -> Result<crate::emitted::f_27_bounds::gc27::TagSeq, rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            batch.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("digest", |__e| {
                let _ = batch.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// `keep`. The contract carries no `ai_desc` for this operation.
        pub fn keep(&mut self, key: crate::emitted::f_27_bounds::gc27::Tag, entry: crate::emitted::f_27_bounds::gc27::Record) -> Result<crate::emitted::f_27_bounds::gc27::Record, rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            key.put(&mut __probe)?;
            entry.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("keep", |__e| {
                let _ = key.put(__e);
                let _ = entry.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// `_get_title`. The contract carries no `ai_desc` for this operation.
        pub fn title(&mut self) -> Result<crate::emitted::f_27_bounds::gc27::Tag, rt::GiopError> {
            let __reply = self.conn.invoke("_get_title", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// `_set_title`. The contract carries no `ai_desc` for this operation.
        pub fn set_title(&mut self, value: crate::emitted::f_27_bounds::gc27::Tag) -> Result<(), rt::GiopError> {
            let mut __probe = rt::Encoder::new(self.conn.endian());
            value.put(&mut __probe)?;
            __probe.finish().map_err(rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("_set_title", |__e| {
                let _ = value.put(__e);
            })?;
            let _ = __reply;
            Ok(())
        }
    }
    
    /// Everything a servant for `IDL:gc27/Ledger:1.0` can fail with.
    ///
    /// `System` is always here, whatever the contract declares: an unknown
    /// key is `OBJECT_NOT_EXIST`, a refused call is `NO_PERMISSION`, a
    /// temporary refusal is `TRANSIENT`, and IDL has no way to declare any
    /// of them. Build one with `rt::raise::*`, which does not produce a
    /// `SystemException` until the completion status is stated — the field
    /// that tells the caller whether a retry is safe, and the one thing a
    /// generator cannot know for a servant.
    ///
    /// The remaining variants are the exceptions named in a `raises`
    /// clause of this interface or of one it inherits. `write` puts the
    /// body §9.4.3.1 describes — repository id first, then the members —
    /// which is exactly what the client side reads back out of
    /// `rt::GiopError::UserException`.
    #[derive(Debug, Clone)]
    pub enum LedgerFault {
        /// A CORBA system exception, with the completion status the
        /// servant chose. Travels as a `SystemException` reply.
        System(rt::SystemException),
        /// IDL exception `IDL:gc27/TooBig:1.0`.
        TooBig(crate::emitted::f_27_bounds::gc27::TooBig),
    }
    impl From<rt::SystemException> for LedgerFault {
        fn from(__ex: rt::SystemException) -> Self {
            Self::System(__ex)
        }
    }
    impl PartialEq for LedgerFault {
        fn eq(&self, __other: &Self) -> bool {
            match (self, __other) {
                (Self::System(__a), Self::System(__b)) => {
                    __a.id == __b.id
                        && __a.minor == __b.minor
                        && __a.completed == __b.completed
                }
                (Self::TooBig(__a), Self::TooBig(__b)) => __a == __b,
                _ => false,
            }
        }
    }
    impl LedgerFault {
        /// The repository id of the user exception this fault carries, or
        /// `None` for a system exception, which carries its own.
        pub fn user_id(&self) -> Option<&'static str> {
            match self {
                Self::System(_) => None,
                Self::TooBig(_) => Some("IDL:gc27/TooBig:1.0"),
            }
        }
        /// Writes this fault into the reply body and says which reply status the
        /// bytes travel under.
        ///
        /// A system exception writes nothing and comes back as `Err`: it is not a
        /// body under a status, it *replaces* the reply (§9.4.3.1), so the
        /// dispatcher hands it to the server to encode instead. That is also why
        /// nothing may be written before the fault is known — the whole buffer
        /// travels under one status.
        pub fn write(&self, __out: &mut rt::Encoder) -> Result<rt::DispatchBody, rt::SystemException> {
            match self {
                Self::System(__ex) => Err(__ex.clone()),
                Self::TooBig(__v) => {
                    __out.put_str("IDL:gc27/TooBig:1.0");
                    __v.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::UserException)
                }
            }
        }
    }
    /// The object-key scheme for `IDL:gc27/Ledger:1.0`, and its reference factory.
    ///
    /// # The keys
    ///
    /// ```text
    /// root                          the default object — oid ""
    /// root ++ "/Ledger/" ++ <oid>    the object named <oid>
    /// ```
    ///
    /// `root` is the key the `rt::Server` was bound with. The derivation is
    /// reversible, so no table of minted keys exists: a reference survives a
    /// restart, and a client cannot make the process grow by looking things
    /// up. The oid is the *whole* remainder after the prefix, so it may
    /// contain `/`, `:`, or the infix itself — there is nothing to escape.
    ///
    /// The infix is the interface name, so two generated skeletons sharing a
    /// root cannot read each other's keys. Use `with_infix` when they are
    /// *meant* to share one key space — an `InterfaceDef` and a `Contained`
    /// over the same repository entry are two interfaces over one object.
    ///
    /// # Minting
    ///
    /// `reference` and `ior` answer with a real IIOP profile, built by
    /// `rt::ObjectHome` — the servant never assembles one, which is why the
    /// GIOP version and profile shape are still decided in exactly one
    /// place. `nil` is the nil reference (§9.3.6), the truthful answer when
    /// there is no such object.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct LedgerRefs {
        home: rt::ObjectHome,
        infix: String,
    }
    impl LedgerRefs {
        /// The repository id minted references advertise.
        pub const TYPE_ID: &'static str = "IDL:gc27/Ledger:1.0";
        /// What separates the root key from the oid.
        pub const KEY_INFIX: &'static str = "/Ledger/";
        /// The scheme rooted at `home`, with the generated infix.
        pub fn new(home: rt::ObjectHome) -> Self {
            Self { home, infix: Self::KEY_INFIX.to_owned() }
        }
        /// The same, with a key space this interface shares with another.
        ///
        /// Two skeletons given the same infix must disagree about `knows`
        /// for every key, or `rt::Servants` will hand a request to
        /// whichever was added first. Sharing a key space is a claim that
        /// the two answer for disjoint sets of objects.
        pub fn with_infix(home: rt::ObjectHome, infix: impl Into<String>) -> Self {
            Self { home, infix: infix.into() }
        }
        /// Where these objects are published.
        pub fn home(&self) -> &rt::ObjectHome { &self.home }
        /// The infix in use, generated or overridden.
        pub fn infix(&self) -> &str { &self.infix }
        /// The default object's key, which is also every other key's prefix.
        pub fn root_key(&self) -> &[u8] { self.home.root_key() }
        /// The object key for `oid`; the empty oid is the root key.
        pub fn key_of(&self, oid: &str) -> Vec<u8> {
            self.home.key_of(&self.infix, oid)
        }
        /// The oid a key addresses, or `None` if it is not one of ours.
        pub fn oid_of<'a>(&self, key: &'a [u8]) -> Option<&'a str> {
            self.home.oid_of(&self.infix, key)
        }
        /// A reference to `oid`, in the form an operation returns.
        pub fn reference(&self, oid: &str) -> rt::ObjRef {
            self.home.reference(Self::TYPE_ID, self.key_of(oid))
        }
        /// The same reference, in the form `LOCATION_FORWARD` carries.
        pub fn ior(&self, oid: &str) -> rt::Ior {
            self.home.ior(Self::TYPE_ID, self.key_of(oid))
        }
        /// The nil reference: there is no such object.
        pub fn nil() -> rt::ObjRef { rt::ObjectHome::nil() }
    }
    /// Which `IDL:gc27/Ledger:1.0` a call is addressed to.
    ///
    /// Every method of the servant trait takes one of these. It carries two
    /// things a servant cannot get any other way: **who it is** (`oid`), and
    /// **how to name its neighbours** (`sibling`) — so an operation that
    /// answers with a reference to another object of this interface can do
    /// it in one call rather than by assembling an IIOP profile.
    ///
    /// The oid borrows the request's own key bytes, so learning who you are
    /// allocates nothing.
    #[derive(Debug, Clone, Copy)]
    pub struct LedgerTarget<'a> {
        oid: &'a str,
        refs: &'a LedgerRefs,
    }
    impl<'a> LedgerTarget<'a> {
        /// The identity `oid` under `refs`.
        pub fn new(oid: &'a str, refs: &'a LedgerRefs) -> Self {
            Self { oid, refs }
        }
        /// Which object this is. The empty oid is the default object,
        /// addressed by the bare root key the server was bound with.
        pub fn oid(&self) -> &'a str { self.oid }
        /// Whether this is the default object.
        pub fn is_default(&self) -> bool { self.oid.is_empty() }
        /// The key scheme, for minting references into other key spaces.
        pub fn refs(&self) -> &'a LedgerRefs { self.refs }
        /// The raw object key this call arrived on.
        pub fn key(&self) -> Vec<u8> { self.refs.key_of(self.oid) }
        /// A reference to *this* object, for handing back one's own address.
        pub fn reference(&self) -> rt::ObjRef { self.refs.reference(self.oid) }
        /// A reference to another object of this interface.
        pub fn sibling(&self, oid: &str) -> rt::ObjRef { self.refs.reference(oid) }
    }
    /// What a servant for `IDL:gc27/Ledger:1.0` must implement.
    ///
    /// One method per operation and per attribute accessor, taking decoded
    /// Rust arguments. Nothing here mentions GIOP: the wire is entirely the
    /// business of `LedgerSkeleton`, which adapts this trait to
    /// `rt::Dispatch`.
    ///
    /// Every method may fail with a `LedgerFault`: a declared user exception,
    /// or a system exception built with `rt::raise::*` — the vocabulary
    /// (`OBJECT_NOT_EXIST`, `NO_PERMISSION`, `BAD_PARAM`, `TRANSIENT`) that
    /// no contract declares and every servant needs.
    ///
    /// # Why every method carries an identity
    ///
    /// The first argument is a `LedgerTarget`: *which* object of this
    /// interface the call was addressed to. One servant therefore answers for
    /// many objects, which is what a process needs to hold a naming context
    /// per key, an `InterfaceDef` per repository id, or a factory per tenant.
    ///
    /// The alternative — a map from key to servant, so each object gets its
    /// own `&mut self` and no argument — is generated too, as
    /// `LedgerObjects`, in terms of this trait. It is the *adapter* and not
    /// the trait because the five hand-written servants in this workspace are
    /// measured, and none of them keeps one value per object: the IR facade
    /// derives its objects from the registry and stores nothing per
    /// reference, and the naming and tenant servants resolve the key on every
    /// call because their operations reach *other* objects — resolving a path,
    /// cloning one model into another. A map-shaped trait can express none of
    /// those; this one expresses the map in ten lines per operation.
    pub trait LedgerServant {
        /// Whether this servant answers for the object `__at` names.
        ///
        /// **Required, with no default.** `rt::Dispatch::knows` defaults to
        /// accepting everything, which is right for a process with one object and
        /// is exactly what stopped a generated skeleton from ever holding more
        /// than one: an unknown key was served as if it were the only object.
        /// There is no answer the generator can give here — the contract says
        /// what an object *does*, never which ones exist — so the question is
        /// asked rather than guessed.
        ///
        /// A single-object servant writes `__at.is_default()`. A `false` here
        /// becomes `OBJECT_NOT_EXIST` for a request and `UNKNOWN_OBJECT` for a
        /// `LocateRequest`, and is also how `rt::Servants` picks between
        /// skeletons sharing one key space.
        fn knows(&self, __at: &LedgerTarget<'_>) -> bool;
        /// Where this request should be sent instead, if anywhere.
        ///
        /// Returning `Some` produces a `LOCATION_FORWARD` (§9.4.3.2), which the
        /// client retries transparently against the new reference.
        ///
        /// # Why the generator defaults this and cannot fill it in
        ///
        /// Everything mechanical about a forward *is* generated: the object key is
        /// decoded, the identity is handed over, and a returned reference becomes
        /// a `LOCATION_FORWARD` reply instead of an invocation. What cannot be
        /// generated is the policy — *when* to redirect and *where to*. IDL
        /// describes operations, types and inheritance; it has no vocabulary for
        /// object location, migration, replication or load, so there is no clause
        /// in any contract from which a forward target could be derived. A
        /// generator that invented one would be inventing deployment.
        ///
        /// So the default is `None` — served here — and it is a default rather
        /// than a silence: this method exists, is documented, and is the one place
        /// to override. Note the two limits the runtime imposes and this cannot
        /// lift: a `oneway` is never forwarded, because there is no reply to carry
        /// the address, and `LOCATION_FORWARD_PERM` is not reachable through
        /// `rt::Dispatch` at all.
        fn forward(&mut self, __at: &LedgerTarget<'_>) -> Option<rt::Ior> {
            let _ = __at;
            None
        }
        /// `digest`. The contract carries no `ai_desc` for this operation.
        fn digest(&mut self, __at: &LedgerTarget<'_>, batch: crate::emitted::f_27_bounds::gc27::BlobSeq) -> Result<crate::emitted::f_27_bounds::gc27::TagSeq, LedgerFault>;
        /// `keep`. The contract carries no `ai_desc` for this operation.
        fn keep(&mut self, __at: &LedgerTarget<'_>, key: crate::emitted::f_27_bounds::gc27::Tag, entry: crate::emitted::f_27_bounds::gc27::Record) -> Result<crate::emitted::f_27_bounds::gc27::Record, LedgerFault>;
        /// `_get_title`. The contract carries no `ai_desc` for this operation.
        fn title(&mut self, __at: &LedgerTarget<'_>) -> Result<crate::emitted::f_27_bounds::gc27::Tag, LedgerFault>;
        /// `_set_title`. The contract carries no `ai_desc` for this operation.
        fn set_title(&mut self, __at: &LedgerTarget<'_>, value: crate::emitted::f_27_bounds::gc27::Tag) -> Result<(), LedgerFault>;
    }
    /// One object of `IDL:gc27/Ledger:1.0`, for a servant that keeps a value per object.
    ///
    /// The same operations as the servant trait with the identity removed:
    /// `&mut self` *is* the object. This is the shape most people reach for
    /// first, and it is the right one whenever objects are created, held and
    /// destroyed rather than derived — an active session, a subscription, a
    /// connection.
    ///
    /// Put a collection of these behind `LedgerObjects` to get a
    /// `LedgerServant`. What it cannot express is an operation that reaches
    /// another object — resolving a path, cloning one model into another — or
    /// a population too large or too derived to materialise; for those,
    /// implement the servant trait directly.
    pub trait LedgerObject {
        /// `digest`. The contract carries no `ai_desc` for this operation.
        fn digest(&mut self, batch: crate::emitted::f_27_bounds::gc27::BlobSeq) -> Result<crate::emitted::f_27_bounds::gc27::TagSeq, LedgerFault>;
        /// `keep`. The contract carries no `ai_desc` for this operation.
        fn keep(&mut self, key: crate::emitted::f_27_bounds::gc27::Tag, entry: crate::emitted::f_27_bounds::gc27::Record) -> Result<crate::emitted::f_27_bounds::gc27::Record, LedgerFault>;
        /// `_get_title`. The contract carries no `ai_desc` for this operation.
        fn title(&mut self) -> Result<crate::emitted::f_27_bounds::gc27::Tag, LedgerFault>;
        /// `_set_title`. The contract carries no `ai_desc` for this operation.
        fn set_title(&mut self, value: crate::emitted::f_27_bounds::gc27::Tag) -> Result<(), LedgerFault>;
    }
    /// A map from oid to one `LedgerObject`, serving `IDL:gc27/Ledger:1.0`.
    ///
    /// The bridge between the two shapes: it implements `LedgerServant` by
    /// looking the identity up and calling the object it found. An oid with
    /// no object is `OBJECT_NOT_EXIST` with `COMPLETED_NO` — nothing ran, so
    /// a client may re-send elsewhere — and `knows` answers from the same map,
    /// so a `LocateRequest` and an invocation cannot disagree.
    ///
    /// The default object is the entry under the empty oid, which is what the
    /// bare root key addresses. A one-object process inserts exactly that.
    #[derive(Debug, Clone)]
    pub struct LedgerObjects<S: LedgerObject> {
        objects: std::collections::BTreeMap<String, S>,
    }
    impl<S: LedgerObject> Default for LedgerObjects<S> {
        fn default() -> Self {
            Self { objects: std::collections::BTreeMap::new() }
        }
    }
    impl<S: LedgerObject> LedgerObjects<S> {
        /// An empty map, which knows no object at all.
        pub fn new() -> Self { <Self as std::default::Default>::default() }
        /// Adds or replaces the object under `oid`, answering what it
        /// displaced. The empty oid is the default object.
        pub fn insert(&mut self, oid: impl Into<String>, object: S) -> Option<S> {
            self.objects.insert(oid.into(), object)
        }
        /// Removes an object, after which its key is `OBJECT_NOT_EXIST`.
        pub fn remove(&mut self, oid: &str) -> Option<S> {
            self.objects.remove(oid)
        }
        /// The object under `oid`, if there is one.
        pub fn get(&self, oid: &str) -> Option<&S> { self.objects.get(oid) }
        /// The object under `oid`, mutably.
        pub fn get_mut(&mut self, oid: &str) -> Option<&mut S> {
            self.objects.get_mut(oid)
        }
        /// Every oid held, in sorted order.
        pub fn oids(&self) -> impl Iterator<Item = &str> {
            self.objects.keys().map(String::as_str)
        }
        /// How many objects are held.
        pub fn len(&self) -> usize { self.objects.len() }
        /// Whether no object is held.
        pub fn is_empty(&self) -> bool { self.objects.is_empty() }
    }
    impl<S: LedgerObject> LedgerServant for LedgerObjects<S> {
        fn knows(&self, __at: &LedgerTarget<'_>) -> bool {
            self.objects.contains_key(__at.oid())
        }
        fn digest(&mut self, __at: &LedgerTarget<'_>, batch: crate::emitted::f_27_bounds::gc27::BlobSeq) -> Result<crate::emitted::f_27_bounds::gc27::TagSeq, LedgerFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.digest(batch),
                None => Err(LedgerFault::System(rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn keep(&mut self, __at: &LedgerTarget<'_>, key: crate::emitted::f_27_bounds::gc27::Tag, entry: crate::emitted::f_27_bounds::gc27::Record) -> Result<crate::emitted::f_27_bounds::gc27::Record, LedgerFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.keep(key, entry),
                None => Err(LedgerFault::System(rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn title(&mut self, __at: &LedgerTarget<'_>) -> Result<crate::emitted::f_27_bounds::gc27::Tag, LedgerFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.title(),
                None => Err(LedgerFault::System(rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn set_title(&mut self, __at: &LedgerTarget<'_>, value: crate::emitted::f_27_bounds::gc27::Tag) -> Result<(), LedgerFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.set_title(value),
                None => Err(LedgerFault::System(rt::raise::object_not_exist().did_not_run())),
            }
        }
    }
    /// Serves `IDL:gc27/Ledger:1.0`: decodes the request, calls the servant, encodes the reply.
    ///
    /// Hand it to `rt::Server::serve` in place of a hand-written
    /// `rt::Dispatch`. What it answers, beyond the contract's own
    /// operations:
    ///
    /// * `_is_a`, from the inheritance chain the registry resolved, because
    ///   an ORB probes with it before it will narrow;
    /// * `_non_existent`, with `false`;
    /// * every other name with `BAD_OPERATION`, including the `_set_` of a
    ///   readonly attribute;
    /// * a body that does not decode with `MARSHAL`.
    ///
    /// A `LedgerFault::System` the servant raises is passed through
    /// unchanged — repository id, minor code and completion status — so the
    /// servant's answer about whether a retry is safe is the one the client
    /// receives.
    ///
    /// # Many objects
    ///
    /// The skeleton owns a `LedgerRefs`, so it takes each request's object
    /// key apart before it looks at the operation and hands the servant the
    /// identity it resolved. A key that does not parse under the scheme is
    /// not ours; a key that parses but names nothing the servant `knows` is
    /// `OBJECT_NOT_EXIST`. Both answers come from generated code, and neither
    /// was possible while a skeleton had no key scheme at all.
    pub struct LedgerSkeleton<S: LedgerServant> {
        /// The implementation invocations are delivered to.
        pub servant: S,
        refs: LedgerRefs,
    }
    impl<S: LedgerServant> LedgerSkeleton<S> {
        /// A skeleton serving `servant`'s objects under `refs`.
        ///
        /// `refs` must be rooted at the key the `rt::Server` was bound
        /// with, or nothing this skeleton parses will match what arrives.
        pub fn new(refs: LedgerRefs, servant: S) -> Self {
            Self { servant, refs }
        }
        /// The key scheme in force, for minting references to these objects.
        pub fn refs(&self) -> &LedgerRefs { &self.refs }
    }
    impl<S: LedgerServant> rt::Dispatch for LedgerSkeleton<S> {
        fn knows(&self, __object_key: &[u8]) -> bool {
            match self.refs.oid_of(__object_key) {
                Some(__oid) => self.servant.knows(&LedgerTarget::new(__oid, &self.refs)),
                None => false,
            }
        }
        fn forward(&mut self, __req: &rt::Request) -> Option<rt::Ior> {
            let __oid = self.refs.oid_of(&__req.object_key)?;
            let __at = LedgerTarget::new(__oid, &self.refs);
            self.servant.forward(&__at)
        }
        fn dispatch_body(
            &mut self,
            __req: &rt::Request,
            __out: &mut rt::Encoder,
        ) -> Result<rt::DispatchBody, rt::SystemException> {
            let __oid = self
                .refs
                .oid_of(&__req.object_key)
                .ok_or_else(rt::SystemException::object_not_exist)?;
            let __at = LedgerTarget::new(__oid, &self.refs);
            let mut __args = __req.body().map_err(|_| rt::SystemException::marshal())?;
            match __req.operation.as_str() {
                "digest" => {
                    let batch: crate::emitted::f_27_bounds::gc27::BlobSeq = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.digest(&__at, batch) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "keep" => {
                    let key: crate::emitted::f_27_bounds::gc27::Tag = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    let entry: crate::emitted::f_27_bounds::gc27::Record = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.keep(&__at, key, entry) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_get_title" => {
                    match self.servant.title(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| rt::SystemException::marshal())?;
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_set_title" => {
                    let value: crate::emitted::f_27_bounds::gc27::Tag = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    match self.servant.set_title(&__at, value) {
                        Ok(()) => {
                            Ok(rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_is_a" => {
                    let __id: String = Cdr::get(&mut __args)
                        .map_err(|_| rt::SystemException::marshal())?;
                    let __answer = matches!(__id.as_str(),
                        "IDL:gc27/Ledger:1.0" |
                        rt::OBJECT_ID);
                    __answer.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::Return)
                }
                "_non_existent" => {
                    false.put(__out).map_err(|_| rt::SystemException::marshal())?;
                    Ok(rt::DispatchBody::Return)
                }
                _ => Err(rt::SystemException::bad_operation()),
            }
        }
        fn dispatch(
            &mut self,
            __req: &rt::Request,
            __out: &mut rt::Encoder,
        ) -> Result<(), rt::SystemException> {
            match self.dispatch_body(__req, __out)? {
                rt::DispatchBody::Return => Ok(()),
                rt::DispatchBody::UserException => {
                    Err(rt::SystemException::unknown_user_exception())
                }
            }
        }
    }

    /// IDL struct `IDL:gc27/Record:1.0`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct Record {
        /// IDL member `label`, marshalled first.
        pub label: crate::emitted::f_27_bounds::gc27::Tag,
        /// IDL member `payload`, marshalled second.
        pub payload: crate::emitted::f_27_bounds::gc27::Blob,
        /// IDL member `wide`, marshalled third.
        pub wide: crate::emitted::f_27_bounds::gc27::WideTag,
    }
    impl Cdr for Record {
        fn put(&self, e: &mut rt::Encoder) -> Result<(), rt::GiopError> {
            self.label.put(e)?;
            self.payload.put(e)?;
            self.wide.put(e)?;
            Ok(())
        }
        fn get(d: &mut rt::Decoder<'_>) -> Result<Self, rt::GiopError> {
            Ok(Self {
                label: Cdr::get(d)?,
                payload: Cdr::get(d)?,
                wide: Cdr::get(d)?,
            })
        }
    }

    /// IDL typedef `IDL:gc27/Tag:1.0`.
    pub type Tag = orbweaver_gen::rt::Bounded<String, 8>;

    /// IDL typedef `IDL:gc27/TagSeq:1.0`.
    pub type TagSeq = orbweaver_gen::rt::Bounded<Vec<crate::emitted::f_27_bounds::gc27::Tag>, 3>;

    /// IDL exception `IDL:gc27/TooBig:1.0`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct TooBig {
        /// IDL member `reason`, marshalled first.
        pub reason: crate::emitted::f_27_bounds::gc27::Tag,
        /// IDL member `offending`, marshalled second.
        pub offending: crate::emitted::f_27_bounds::gc27::Blob,
    }
    impl Cdr for TooBig {
        fn put(&self, e: &mut rt::Encoder) -> Result<(), rt::GiopError> {
            self.reason.put(e)?;
            self.offending.put(e)?;
            Ok(())
        }
        fn get(d: &mut rt::Decoder<'_>) -> Result<Self, rt::GiopError> {
            Ok(Self {
                reason: Cdr::get(d)?,
                offending: Cdr::get(d)?,
            })
        }
    }

    /// IDL typedef `IDL:gc27/WideTag:1.0`.
    pub type WideTag = orbweaver_gen::rt::Bounded<orbweaver_gen::rt::WString, 4>;

}
