//! Generated by orbweaver-gen from the registry.
//!
//! Names and order only; every marshalling decision is a call into
//! `orbweaver_gen::rt`, so the wire knowledge exists once.
//!
//! Each interface yields a client stub, a servant trait and a
//! skeleton that adapts the trait to `orbweaver_gen::rt::Dispatch`.
#![cfg_attr(rustfmt, rustfmt::skip)]
#![forbid(unsafe_code)]
#![deny(missing_docs)]
#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]
#![allow(clippy::wrong_self_convention, clippy::should_implement_trait, clippy::len_without_is_empty, clippy::too_many_arguments)]

/// IDL module `gclint`.
pub mod gclint {
    use ::orbweaver_gen::rt::{self as __rt, Cdr as __Cdr};
    /// IDL struct `IDL:gclint/Pair:1.0`.
    #[derive(Debug, Clone, PartialEq)]
    pub struct Pair {
        /// IDL member `a`, marshalled first.
        pub a: i32,
        /// IDL member `b`, marshalled second.
        pub b: i32,
    }
    impl __Cdr for Pair {
        fn put(&self, __e: &mut __rt::Encoder) -> ::std::result::Result<(), __rt::GiopError> {
            self.a.put(__e)?;
            self.b.put(__e)?;
            Ok(())
        }
        fn get(__d: &mut __rt::Decoder<'_>) -> ::std::result::Result<Self, __rt::GiopError> {
            Ok(Self {
                a: __Cdr::get(__d)?,
                b: __Cdr::get(__d)?,
            })
        }
    }

    /// One operation per naming convention the target language claims
    ///
    /// Client stub for `IDL:gclint/Probe:1.0`.
    ///
    /// Static twin of the dynamic path; §8 requires their bytes to be
    /// identical, and the harness holds them to it.
    ///
    /// Generic over the invoker on purpose (PLAN §7.4 I1): over a raw
    /// `Connection` inside the trust boundary, or over the guarded
    /// wrapper at it — a stub hard-wired to the transport would be the
    /// §4.7 bypass in compiled form.
    pub struct ProbeClient<C: __rt::Invoker> {
        /// What calls travel over.
        pub conn: C,
    }
    impl<C: __rt::Invoker> ProbeClient<C> {
        /// A stub over an open invoker.
        pub fn new(__conn: C) -> Self { Self { conn: __conn } }
        /// This probe's first number increased by an amount
        ///
        /// `add` on the wire.
        pub fn add(&mut self, v: i32) -> ::std::result::Result<i32, __rt::GiopError> {
            let mut __probe = __rt::Encoder::new(self.conn.endian());
            v.put(&mut __probe)?;
            __probe.finish().map_err(__rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("add", |__e| {
                let _ = v.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// This probe's state viewed as a pair
        ///
        /// `as_pair` on the wire.
        pub fn as_pair(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, __rt::GiopError> {
            let __reply = self.conn.invoke("as_pair", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// A copy of this probe's state
        ///
        /// `clone` on the wire.
        pub fn clone(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, __rt::GiopError> {
            let __reply = self.conn.invoke("clone", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// The pair this probe starts from
        ///
        /// `default` on the wire.
        pub fn default(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, __rt::GiopError> {
            let __reply = self.conn.invoke("default", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// Whether the given pair equals this probe's state
        ///
        /// `eq` on the wire.
        pub fn eq(&mut self, other: crate::emitted::f_gen_target_lints::gclint::Pair) -> ::std::result::Result<bool, __rt::GiopError> {
            let mut __probe = __rt::Encoder::new(self.conn.endian());
            other.put(&mut __probe)?;
            __probe.finish().map_err(__rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("eq", |__e| {
                let _ = other.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// The pair a textual rendering denotes
        ///
        /// `from_text` on the wire.
        pub fn from_text(&mut self, t: ::std::string::String) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, __rt::GiopError> {
            let mut __probe = __rt::Encoder::new(self.conn.endian());
            t.put(&mut __probe)?;
            __probe.finish().map_err(__rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("from_text", |__e| {
                let _ = t.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// The number held at a position
        ///
        /// `index` on the wire.
        pub fn index(&mut self, v: i32) -> ::std::result::Result<i32, __rt::GiopError> {
            let mut __probe = __rt::Encoder::new(self.conn.endian());
            v.put(&mut __probe)?;
            __probe.finish().map_err(__rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("index", |__e| {
                let _ = v.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// This probe's state consumed into a pair
        ///
        /// `into_pair` on the wire.
        pub fn into_pair(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, __rt::GiopError> {
            let __reply = self.conn.invoke("into_pair", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// Whether the probe will answer right now
        ///
        /// `is_ready` on the wire.
        pub fn is_ready(&mut self) -> ::std::result::Result<bool, __rt::GiopError> {
            let __reply = self.conn.invoke("is_ready", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// How many numbers this probe holds
        ///
        /// `len` on the wire.
        pub fn len(&mut self) -> ::std::result::Result<i32, __rt::GiopError> {
            let __reply = self.conn.invoke("len", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// This probe's first number with its sign flipped
        ///
        /// `neg` on the wire.
        pub fn neg(&mut self) -> ::std::result::Result<i32, __rt::GiopError> {
            let __reply = self.conn.invoke("neg", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// The next pair in sequence
        ///
        /// `next` on the wire.
        pub fn next(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, __rt::GiopError> {
            let __reply = self.conn.invoke("next", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// This probe's first number reduced by an amount
        ///
        /// `sub` on the wire.
        pub fn sub(&mut self, v: i32) -> ::std::result::Result<i32, __rt::GiopError> {
            let mut __probe = __rt::Encoder::new(self.conn.endian());
            v.put(&mut __probe)?;
            __probe.finish().map_err(__rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("sub", |__e| {
                let _ = v.put(__e);
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// A textual rendering of this probe
        ///
        /// `to_text` on the wire.
        pub fn to_text(&mut self) -> ::std::result::Result<::std::string::String, __rt::GiopError> {
            let __reply = self.conn.invoke("to_text", |__e| {
            })?;
            let mut __body = __reply.body()?;
            let __r0 = __Cdr::get(&mut __body)?;
            Ok(__r0)
        }
        /// Takes more parameters than the target's style lint allows for
        ///
        /// `wide` on the wire.
        pub fn wide(&mut self, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32) -> ::std::result::Result<(), __rt::GiopError> {
            let mut __probe = __rt::Encoder::new(self.conn.endian());
            a1.put(&mut __probe)?;
            a2.put(&mut __probe)?;
            a3.put(&mut __probe)?;
            a4.put(&mut __probe)?;
            a5.put(&mut __probe)?;
            a6.put(&mut __probe)?;
            a7.put(&mut __probe)?;
            a8.put(&mut __probe)?;
            a9.put(&mut __probe)?;
            __probe.finish().map_err(__rt::GiopError::Cdr)?;
            let __reply = self.conn.invoke("wide", |__e| {
                let _ = a1.put(__e);
                let _ = a2.put(__e);
                let _ = a3.put(__e);
                let _ = a4.put(__e);
                let _ = a5.put(__e);
                let _ = a6.put(__e);
                let _ = a7.put(__e);
                let _ = a8.put(__e);
                let _ = a9.put(__e);
            })?;
            let _ = __reply;
            Ok(())
        }
    }
    
    /// Everything a servant for `IDL:gclint/Probe:1.0` can fail with.
    ///
    /// `System` is always here, whatever the contract declares: an unknown
    /// key is `OBJECT_NOT_EXIST`, a refused call is `NO_PERMISSION`, a
    /// temporary refusal is `TRANSIENT`, and IDL has no way to declare any
    /// of them. Build one with `orbweaver_gen::rt::raise::*`, which does not produce a
    /// `SystemException` until the completion status is stated — the field
    /// that tells the caller whether a retry is safe, and the one thing a
    /// generator cannot know for a servant.
    ///
    /// This interface names no `raises` clause, so `System` is the only
    /// variant. It is still an inhabited type: a servant that cannot fail
    /// is not a servant anybody can write.
    #[derive(Debug, Clone)]
    pub enum ProbeFault {
        /// A CORBA system exception, with the completion status the
        /// servant chose. Travels as a `SystemException` reply.
        System(__rt::SystemException),
    }
    impl ::std::convert::From<__rt::SystemException> for ProbeFault {
        fn from(__ex: __rt::SystemException) -> Self {
            Self::System(__ex)
        }
    }
    impl ::std::cmp::PartialEq for ProbeFault {
        fn eq(&self, __other: &Self) -> bool {
            match (self, __other) {
                (Self::System(__a), Self::System(__b)) => {
                    __a.id == __b.id
                        && __a.minor == __b.minor
                        && __a.completed == __b.completed
                }
            }
        }
    }
    impl ProbeFault {
        /// The repository id of the user exception this fault carries, or
        /// `None` for a system exception, which carries its own.
        pub fn user_id(&self) -> ::std::option::Option<&'static str> {
            match self {
                Self::System(_) => None,
            }
        }
        /// Writes this fault into the reply body and says which reply status the
        /// bytes travel under.
        ///
        /// A system exception writes nothing and comes back as `Err`: it is not a
        /// body under a status, it *replaces* the reply (§9.4.3.1), so the
        /// dispatcher hands it to the server to encode instead. That is also why
        /// nothing may be written before the fault is known — the whole buffer
        /// travels under one status.
        pub fn write(&self, __out: &mut __rt::Encoder) -> ::std::result::Result<__rt::DispatchBody, __rt::SystemException> {
            let _ = __out;
            match self {
                Self::System(__ex) => Err(__ex.clone()),
            }
        }
    }
    /// The object-key scheme for `IDL:gclint/Probe:1.0`, and its reference factory.
    ///
    /// # The keys
    ///
    /// ```text
    /// root                          the default object — oid ""
    /// root ++ "/Probe/" ++ <oid>    the object named <oid>
    /// ```
    ///
    /// `root` is the key the `orbweaver_gen::rt::Server` was bound with. The derivation is
    /// reversible, so no table of minted keys exists: a reference survives a
    /// restart, and a client cannot make the process grow by looking things
    /// up. The oid is the *whole* remainder after the prefix, so it may
    /// contain `/`, `:`, or the infix itself — there is nothing to escape.
    ///
    /// The infix is the interface name, so two generated skeletons sharing a
    /// root cannot read each other's keys. Use `with_infix` when they are
    /// *meant* to share one key space — an `InterfaceDef` and a `Contained`
    /// over the same repository entry are two interfaces over one object.
    ///
    /// # Minting
    ///
    /// `reference` and `ior` answer with a real IIOP profile, built by
    /// `orbweaver_gen::rt::ObjectHome` — the servant never assembles one, which is why the
    /// GIOP version and profile shape are still decided in exactly one
    /// place. `nil` is the nil reference (§9.3.6), the truthful answer when
    /// there is no such object.
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ProbeRefs {
        home: __rt::ObjectHome,
        infix: ::std::string::String,
    }
    impl ProbeRefs {
        /// The repository id minted references advertise.
        pub const TYPE_ID: &'static str = "IDL:gclint/Probe:1.0";
        /// What separates the root key from the oid.
        pub const KEY_INFIX: &'static str = "/Probe/";
        /// The scheme rooted at `home`, with the generated infix.
        pub fn new(__home: __rt::ObjectHome) -> Self {
            Self { home: __home, infix: Self::KEY_INFIX.to_owned() }
        }
        /// The same, with a key space this interface shares with another.
        ///
        /// Two skeletons given the same infix must disagree about `knows`
        /// for every key, or `orbweaver_gen::rt::Servants` will hand a request to
        /// whichever was added first. Sharing a key space is a claim that
        /// the two answer for disjoint sets of objects.
        pub fn with_infix(__home: __rt::ObjectHome, __infix: impl ::std::convert::Into<::std::string::String>) -> Self {
            Self { home: __home, infix: __infix.into() }
        }
        /// Where these objects are published.
        pub fn home(&self) -> &__rt::ObjectHome { &self.home }
        /// The infix in use, generated or overridden.
        pub fn infix(&self) -> &str { &self.infix }
        /// The default object's key, which is also every other key's prefix.
        pub fn root_key(&self) -> &[u8] { self.home.root_key() }
        /// The object key for `oid`; the empty oid is the root key.
        pub fn key_of(&self, __oid: &str) -> ::std::vec::Vec<u8> {
            self.home.key_of(&self.infix, __oid)
        }
        /// The oid a key addresses, or `None` if it is not one of ours.
        pub fn oid_of<'a>(&self, __key: &'a [u8]) -> ::std::option::Option<&'a str> {
            self.home.oid_of(&self.infix, __key)
        }
        /// A reference to `oid`, in the form an operation returns.
        pub fn reference(&self, __oid: &str) -> __rt::ObjRef {
            self.home.reference(Self::TYPE_ID, self.key_of(__oid))
        }
        /// The same reference, in the form `LOCATION_FORWARD` carries.
        pub fn ior(&self, __oid: &str) -> __rt::Ior {
            self.home.ior(Self::TYPE_ID, self.key_of(__oid))
        }
        /// The nil reference: there is no such object.
        pub fn nil() -> __rt::ObjRef { __rt::ObjectHome::nil() }
    }
    /// Which `IDL:gclint/Probe:1.0` a call is addressed to.
    ///
    /// Every method of the servant trait takes one of these. It carries two
    /// things a servant cannot get any other way: **who it is** (`oid`), and
    /// **how to name its neighbours** (`sibling`) — so an operation that
    /// answers with a reference to another object of this interface can do
    /// it in one call rather than by assembling an IIOP profile.
    ///
    /// The oid borrows the request's own key bytes, so learning who you are
    /// allocates nothing.
    #[derive(Debug, Clone, Copy)]
    pub struct ProbeTarget<'a> {
        oid: &'a str,
        refs: &'a ProbeRefs,
    }
    impl<'a> ProbeTarget<'a> {
        /// The identity `oid` under `refs`.
        pub fn new(__oid: &'a str, __refs: &'a ProbeRefs) -> Self {
            Self { oid: __oid, refs: __refs }
        }
        /// Which object this is. The empty oid is the default object,
        /// addressed by the bare root key the server was bound with.
        pub fn oid(&self) -> &'a str { self.oid }
        /// Whether this is the default object.
        pub fn is_default(&self) -> bool { self.oid.is_empty() }
        /// The key scheme, for minting references into other key spaces.
        pub fn refs(&self) -> &'a ProbeRefs { self.refs }
        /// The raw object key this call arrived on.
        pub fn key(&self) -> ::std::vec::Vec<u8> { self.refs.key_of(self.oid) }
        /// A reference to *this* object, for handing back one's own address.
        pub fn reference(&self) -> __rt::ObjRef { self.refs.reference(self.oid) }
        /// A reference to another object of this interface.
        pub fn sibling(&self, __oid: &str) -> __rt::ObjRef { self.refs.reference(__oid) }
    }
    /// One operation per naming convention the target language claims
    ///
    /// What a servant for `IDL:gclint/Probe:1.0` must implement.
    ///
    /// One method per operation and per attribute accessor, taking decoded
    /// Rust arguments. Nothing here mentions GIOP: the wire is entirely the
    /// business of `ProbeSkeleton`, which adapts this trait to
    /// `orbweaver_gen::rt::Dispatch`.
    ///
    /// Every method may fail with a `ProbeFault`: a declared user exception,
    /// or a system exception built with `orbweaver_gen::rt::raise::*` — the vocabulary
    /// (`OBJECT_NOT_EXIST`, `NO_PERMISSION`, `BAD_PARAM`, `TRANSIENT`) that
    /// no contract declares and every servant needs.
    ///
    /// # Why every method carries an identity
    ///
    /// The first argument is a `ProbeTarget`: *which* object of this
    /// interface the call was addressed to. One servant therefore answers for
    /// many objects, which is what a process needs to hold a naming context
    /// per key, an `InterfaceDef` per repository id, or a factory per tenant.
    ///
    /// The alternative — a map from key to servant, so each object gets its
    /// own `&mut self` and no argument — is generated too, as
    /// `ProbeObjects`, in terms of this trait. It is the *adapter* and not
    /// the trait because the five hand-written servants in this workspace are
    /// measured, and none of them keeps one value per object: the IR facade
    /// derives its objects from the registry and stores nothing per
    /// reference, and the naming and tenant servants resolve the key on every
    /// call because their operations reach *other* objects — resolving a path,
    /// cloning one model into another. A map-shaped trait can express none of
    /// those; this one expresses the map in ten lines per operation.
    pub trait ProbeServant {
        /// Whether this servant answers for the object `__at` names.
        ///
        /// **Required, with no default.** `orbweaver_gen::rt::Dispatch::knows` defaults to
        /// accepting everything, which is right for a process with one object and
        /// is exactly what stopped a generated skeleton from ever holding more
        /// than one: an unknown key was served as if it were the only object.
        /// There is no answer the generator can give here — the contract says
        /// what an object *does*, never which ones exist — so the question is
        /// asked rather than guessed.
        ///
        /// A single-object servant writes `__at.is_default()`. A `false` here
        /// becomes `OBJECT_NOT_EXIST` for a request and `UNKNOWN_OBJECT` for a
        /// `LocateRequest`, and is also how `orbweaver_gen::rt::Servants` picks between
        /// skeletons sharing one key space.
        fn knows(&self, __at: &ProbeTarget<'_>) -> bool;
        /// Where this request should be sent instead, if anywhere.
        ///
        /// Returning `Some` produces a `LOCATION_FORWARD` (§9.4.3.2), which the
        /// client retries transparently against the new reference.
        ///
        /// # Why the generator defaults this and cannot fill it in
        ///
        /// Everything mechanical about a forward *is* generated: the object key is
        /// decoded, the identity is handed over, and a returned reference becomes
        /// a `LOCATION_FORWARD` reply instead of an invocation. What cannot be
        /// generated is the policy — *when* to redirect and *where to*. IDL
        /// describes operations, types and inheritance; it has no vocabulary for
        /// object location, migration, replication or load, so there is no clause
        /// in any contract from which a forward target could be derived. A
        /// generator that invented one would be inventing deployment.
        ///
        /// So the default is `None` — served here — and it is a default rather
        /// than a silence: this method exists, is documented, and is the one place
        /// to override. Note the one limit the runtime imposes and this cannot
        /// lift: a `oneway` is never forwarded, because there is no reply to carry
        /// the address. This hook is the *temporary* forward; an object that has
        /// moved for good says so through `redirect`, below.
        fn forward(&mut self, __at: &ProbeTarget<'_>) -> ::std::option::Option<__rt::Ior> {
            let _ = __at;
            None
        }
        /// Where this request should be sent instead, and whether for good.
        ///
        /// The method the runtime actually asks. `orbweaver_gen::rt::Forward::Temporary` is a
        /// `LOCATION_FORWARD`; `orbweaver_gen::rt::Forward::Permanent` is a
        /// `LOCATION_FORWARD_PERM` (§9.4.3.2, GIOP 1.2 — a 1.0/1.1 peer is told
        /// the temporary form, its reply-status enumeration having no other),
        /// and is the one thing a servant can say that lets a client replace the
        /// reference it holds rather than keep the old one as a fallback.
        ///
        /// Defaults to `forward` wrapped as temporary, so a servant that
        /// overrides only `forward` behaves as it always did. Override this one
        /// to say *permanent*; there is no reason to override both.
        fn redirect(&mut self, __at: &ProbeTarget<'_>) -> ::std::option::Option<__rt::Forward> {
            self.forward(__at).map(__rt::Forward::Temporary)
        }
        /// This probe's first number increased by an amount
        ///
        /// `add` on the wire.
        fn add(&mut self, __at: &ProbeTarget<'_>, v: i32) -> ::std::result::Result<i32, ProbeFault>;
        /// This probe's state viewed as a pair
        ///
        /// `as_pair` on the wire.
        fn as_pair(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// A copy of this probe's state
        ///
        /// `clone` on the wire.
        fn clone(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// The pair this probe starts from
        ///
        /// `default` on the wire.
        fn default(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// Whether the given pair equals this probe's state
        ///
        /// `eq` on the wire.
        fn eq(&mut self, __at: &ProbeTarget<'_>, other: crate::emitted::f_gen_target_lints::gclint::Pair) -> ::std::result::Result<bool, ProbeFault>;
        /// The pair a textual rendering denotes
        ///
        /// `from_text` on the wire.
        fn from_text(&mut self, __at: &ProbeTarget<'_>, t: ::std::string::String) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// The number held at a position
        ///
        /// `index` on the wire.
        fn index(&mut self, __at: &ProbeTarget<'_>, v: i32) -> ::std::result::Result<i32, ProbeFault>;
        /// This probe's state consumed into a pair
        ///
        /// `into_pair` on the wire.
        fn into_pair(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// Whether the probe will answer right now
        ///
        /// `is_ready` on the wire.
        fn is_ready(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<bool, ProbeFault>;
        /// How many numbers this probe holds
        ///
        /// `len` on the wire.
        fn len(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<i32, ProbeFault>;
        /// This probe's first number with its sign flipped
        ///
        /// `neg` on the wire.
        fn neg(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<i32, ProbeFault>;
        /// The next pair in sequence
        ///
        /// `next` on the wire.
        fn next(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// This probe's first number reduced by an amount
        ///
        /// `sub` on the wire.
        fn sub(&mut self, __at: &ProbeTarget<'_>, v: i32) -> ::std::result::Result<i32, ProbeFault>;
        /// A textual rendering of this probe
        ///
        /// `to_text` on the wire.
        fn to_text(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<::std::string::String, ProbeFault>;
        /// Takes more parameters than the target's style lint allows for
        ///
        /// `wide` on the wire.
        fn wide(&mut self, __at: &ProbeTarget<'_>, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32) -> ::std::result::Result<(), ProbeFault>;
    }
    /// One object of `IDL:gclint/Probe:1.0`, for a servant that keeps a value per object.
    ///
    /// The same operations as the servant trait with the identity removed:
    /// `&mut self` *is* the object. This is the shape most people reach for
    /// first, and it is the right one whenever objects are created, held and
    /// destroyed rather than derived — an active session, a subscription, a
    /// connection.
    ///
    /// Put a collection of these behind `ProbeObjects` to get a
    /// `ProbeServant`. What it cannot express is an operation that reaches
    /// another object — resolving a path, cloning one model into another — or
    /// a population too large or too derived to materialise; for those,
    /// implement the servant trait directly.
    pub trait ProbeObject {
        /// This probe's first number increased by an amount
        ///
        /// `add` on the wire.
        fn add(&mut self, v: i32) -> ::std::result::Result<i32, ProbeFault>;
        /// This probe's state viewed as a pair
        ///
        /// `as_pair` on the wire.
        fn as_pair(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// A copy of this probe's state
        ///
        /// `clone` on the wire.
        fn clone(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// The pair this probe starts from
        ///
        /// `default` on the wire.
        fn default(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// Whether the given pair equals this probe's state
        ///
        /// `eq` on the wire.
        fn eq(&mut self, other: crate::emitted::f_gen_target_lints::gclint::Pair) -> ::std::result::Result<bool, ProbeFault>;
        /// The pair a textual rendering denotes
        ///
        /// `from_text` on the wire.
        fn from_text(&mut self, t: ::std::string::String) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// The number held at a position
        ///
        /// `index` on the wire.
        fn index(&mut self, v: i32) -> ::std::result::Result<i32, ProbeFault>;
        /// This probe's state consumed into a pair
        ///
        /// `into_pair` on the wire.
        fn into_pair(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// Whether the probe will answer right now
        ///
        /// `is_ready` on the wire.
        fn is_ready(&mut self) -> ::std::result::Result<bool, ProbeFault>;
        /// How many numbers this probe holds
        ///
        /// `len` on the wire.
        fn len(&mut self) -> ::std::result::Result<i32, ProbeFault>;
        /// This probe's first number with its sign flipped
        ///
        /// `neg` on the wire.
        fn neg(&mut self) -> ::std::result::Result<i32, ProbeFault>;
        /// The next pair in sequence
        ///
        /// `next` on the wire.
        fn next(&mut self) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault>;
        /// This probe's first number reduced by an amount
        ///
        /// `sub` on the wire.
        fn sub(&mut self, v: i32) -> ::std::result::Result<i32, ProbeFault>;
        /// A textual rendering of this probe
        ///
        /// `to_text` on the wire.
        fn to_text(&mut self) -> ::std::result::Result<::std::string::String, ProbeFault>;
        /// Takes more parameters than the target's style lint allows for
        ///
        /// `wide` on the wire.
        fn wide(&mut self, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32) -> ::std::result::Result<(), ProbeFault>;
    }
    /// A map from oid to one `ProbeObject`, serving `IDL:gclint/Probe:1.0`.
    ///
    /// The bridge between the two shapes: it implements `ProbeServant` by
    /// looking the identity up and calling the object it found. An oid with
    /// no object is `OBJECT_NOT_EXIST` with `COMPLETED_NO` — nothing ran, so
    /// a client may re-send elsewhere — and `knows` answers from the same map,
    /// so a `LocateRequest` and an invocation cannot disagree.
    ///
    /// The default object is the entry under the empty oid, which is what the
    /// bare root key addresses. A one-object process inserts exactly that.
    #[derive(Debug, Clone)]
    pub struct ProbeObjects<S: ProbeObject> {
        objects: ::std::collections::BTreeMap<::std::string::String, S>,
    }
    impl<S: ProbeObject> ::std::default::Default for ProbeObjects<S> {
        fn default() -> Self {
            Self { objects: ::std::collections::BTreeMap::new() }
        }
    }
    impl<S: ProbeObject> ProbeObjects<S> {
        /// An empty map, which knows no object at all.
        pub fn new() -> Self { <Self as ::std::default::Default>::default() }
        /// Adds or replaces the object under `oid`, answering what it
        /// displaced. The empty oid is the default object.
        pub fn insert(&mut self, __oid: impl ::std::convert::Into<::std::string::String>, __object: S) -> ::std::option::Option<S> {
            self.objects.insert(__oid.into(), __object)
        }
        /// Removes an object, after which its key is `OBJECT_NOT_EXIST`.
        pub fn remove(&mut self, __oid: &str) -> ::std::option::Option<S> {
            self.objects.remove(__oid)
        }
        /// The object under `oid`, if there is one.
        pub fn get(&self, __oid: &str) -> ::std::option::Option<&S> { self.objects.get(__oid) }
        /// The object under `oid`, mutably.
        pub fn get_mut(&mut self, __oid: &str) -> ::std::option::Option<&mut S> {
            self.objects.get_mut(__oid)
        }
        /// Every oid held, in sorted order.
        pub fn oids(&self) -> impl ::std::iter::Iterator<Item = &str> {
            self.objects.keys().map(::std::string::String::as_str)
        }
        /// How many objects are held.
        pub fn len(&self) -> usize { self.objects.len() }
        /// Whether no object is held.
        pub fn is_empty(&self) -> bool { self.objects.is_empty() }
    }
    impl<S: ProbeObject> ProbeServant for ProbeObjects<S> {
        fn knows(&self, __at: &ProbeTarget<'_>) -> bool {
            self.objects.contains_key(__at.oid())
        }
        fn add(&mut self, __at: &ProbeTarget<'_>, v: i32) -> ::std::result::Result<i32, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.add(v),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn as_pair(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.as_pair(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn clone(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.clone(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn default(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.default(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn eq(&mut self, __at: &ProbeTarget<'_>, other: crate::emitted::f_gen_target_lints::gclint::Pair) -> ::std::result::Result<bool, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.eq(other),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn from_text(&mut self, __at: &ProbeTarget<'_>, t: ::std::string::String) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.from_text(t),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn index(&mut self, __at: &ProbeTarget<'_>, v: i32) -> ::std::result::Result<i32, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.index(v),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn into_pair(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.into_pair(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn is_ready(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<bool, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.is_ready(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn len(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<i32, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.len(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn neg(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<i32, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.neg(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn next(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<crate::emitted::f_gen_target_lints::gclint::Pair, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.next(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn sub(&mut self, __at: &ProbeTarget<'_>, v: i32) -> ::std::result::Result<i32, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.sub(v),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn to_text(&mut self, __at: &ProbeTarget<'_>) -> ::std::result::Result<::std::string::String, ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.to_text(),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
        fn wide(&mut self, __at: &ProbeTarget<'_>, a1: i32, a2: i32, a3: i32, a4: i32, a5: i32, a6: i32, a7: i32, a8: i32, a9: i32) -> ::std::result::Result<(), ProbeFault> {
            match self.objects.get_mut(__at.oid()) {
                Some(__o) => __o.wide(a1, a2, a3, a4, a5, a6, a7, a8, a9),
                None => Err(ProbeFault::System(__rt::raise::object_not_exist().did_not_run())),
            }
        }
    }
    /// Serves `IDL:gclint/Probe:1.0`: decodes the request, calls the servant, encodes the reply.
    ///
    /// Hand it to `orbweaver_gen::rt::Server::serve` in place of a hand-written
    /// `orbweaver_gen::rt::Dispatch`. What it answers, beyond the contract's own
    /// operations:
    ///
    /// * `_is_a`, from the inheritance chain the registry resolved, because
    ///   an ORB probes with it before it will narrow;
    /// * `_non_existent`, with `false`;
    /// * every other name with `BAD_OPERATION`, including the `_set_` of a
    ///   readonly attribute;
    /// * a body that does not decode with `MARSHAL`.
    ///
    /// A `ProbeFault::System` the servant raises is passed through
    /// unchanged — repository id, minor code and completion status — so the
    /// servant's answer about whether a retry is safe is the one the client
    /// receives.
    ///
    /// # Many objects
    ///
    /// The skeleton owns a `ProbeRefs`, so it takes each request's object
    /// key apart before it looks at the operation and hands the servant the
    /// identity it resolved. A key that does not parse under the scheme is
    /// not ours; a key that parses but names nothing the servant `knows` is
    /// `OBJECT_NOT_EXIST`. Both answers come from generated code, and neither
    /// was possible while a skeleton had no key scheme at all.
    pub struct ProbeSkeleton<S: ProbeServant> {
        /// The implementation invocations are delivered to.
        pub servant: S,
        refs: ProbeRefs,
    }
    impl<S: ProbeServant> ProbeSkeleton<S> {
        /// A skeleton serving `servant`'s objects under `refs`.
        ///
        /// `refs` must be rooted at the key the `orbweaver_gen::rt::Server` was bound
        /// with, or nothing this skeleton parses will match what arrives.
        pub fn new(__refs: ProbeRefs, __servant: S) -> Self {
            Self { servant: __servant, refs: __refs }
        }
        /// The key scheme in force, for minting references to these objects.
        pub fn refs(&self) -> &ProbeRefs { &self.refs }
    }
    impl<S: ProbeServant> __rt::Dispatch for ProbeSkeleton<S> {
        fn knows(&self, __object_key: &[u8]) -> bool {
            match self.refs.oid_of(__object_key) {
                Some(__oid) => self.servant.knows(&ProbeTarget::new(__oid, &self.refs)),
                None => false,
            }
        }
        fn forward(&mut self, __req: &__rt::Request) -> ::std::option::Option<__rt::Ior> {
            let __oid = self.refs.oid_of(&__req.object_key)?;
            let __at = ProbeTarget::new(__oid, &self.refs);
            self.servant.forward(&__at)
        }
        fn redirect(&mut self, __req: &__rt::Request) -> ::std::option::Option<__rt::Forward> {
            let __oid = self.refs.oid_of(&__req.object_key)?;
            let __at = ProbeTarget::new(__oid, &self.refs);
            self.servant.redirect(&__at)
        }
        fn dispatch_body(
            &mut self,
            __req: &__rt::Request,
            __out: &mut __rt::Encoder,
        ) -> ::std::result::Result<__rt::DispatchBody, __rt::SystemException> {
            let __oid = self
                .refs
                .oid_of(&__req.object_key)
                .ok_or_else(__rt::SystemException::object_not_exist)?;
            let __at = ProbeTarget::new(__oid, &self.refs);
            let mut __args = __req.body().map_err(|_| __rt::SystemException::marshal())?;
            match __req.operation.as_str() {
                "add" => {
                    let v: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    match self.servant.add(&__at, v) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "as_pair" => {
                    match self.servant.as_pair(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "clone" => {
                    match self.servant.clone(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "default" => {
                    match self.servant.default(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "eq" => {
                    let other: crate::emitted::f_gen_target_lints::gclint::Pair = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    match self.servant.eq(&__at, other) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "from_text" => {
                    let t: ::std::string::String = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    match self.servant.from_text(&__at, t) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "index" => {
                    let v: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    match self.servant.index(&__at, v) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "into_pair" => {
                    match self.servant.into_pair(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "is_ready" => {
                    match self.servant.is_ready(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "len" => {
                    match self.servant.len(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "neg" => {
                    match self.servant.neg(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "next" => {
                    match self.servant.next(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "sub" => {
                    let v: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    match self.servant.sub(&__at, v) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "to_text" => {
                    match self.servant.to_text(&__at) {
                        Ok(__r0) => {
                            __r0.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "wide" => {
                    let a1: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let a2: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let a3: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let a4: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let a5: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let a6: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let a7: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let a8: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let a9: i32 = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    match self.servant.wide(&__at, a1, a2, a3, a4, a5, a6, a7, a8, a9) {
                        Ok(()) => {
                            Ok(__rt::DispatchBody::Return)
                        }
                        Err(__f) => __f.write(__out),
                    }
                }
                "_is_a" => {
                    let __id: ::std::string::String = __Cdr::get(&mut __args)
                        .map_err(|_| __rt::SystemException::marshal())?;
                    let __answer = matches!(__id.as_str(),
                        "IDL:gclint/Probe:1.0" |
                        __rt::OBJECT_ID);
                    __answer.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                    Ok(__rt::DispatchBody::Return)
                }
                "_non_existent" => {
                    false.put(__out).map_err(|_| __rt::SystemException::marshal())?;
                    Ok(__rt::DispatchBody::Return)
                }
                _ => Err(__rt::SystemException::bad_operation()),
            }
        }
        fn dispatch(
            &mut self,
            __req: &__rt::Request,
            __out: &mut __rt::Encoder,
        ) -> ::std::result::Result<(), __rt::SystemException> {
            match self.dispatch_body(__req, __out)? {
                __rt::DispatchBody::Return => Ok(()),
                __rt::DispatchBody::UserException => {
                    Err(__rt::SystemException::unknown_user_exception())
                }
            }
        }
    }

}
