//! The vector side of `search_interfaces`: a versioned on-disk cache, cosine
//! similarity, and a ranker — and **no model**.
//!
//! D003 (APPROVED 2026-08-14) adopts embeddings as an *external command*, in
//! the `gen_claude.sh` mold: `spikes/embed.sh` POSTs to an embeddings HTTP API
//! and prints vectors, and this module reads them out of a cache file. That is
//! the whole dependency story. **`cargo tree` gains nothing from this module**
//! — no inference runtime, no weights, no HTTP client. The model is a separate
//! process whose output we read, the same boundary category as `omniidl` as a
//! conformance oracle.
//!
//! Everything here is first-party: the file format is defined below and parsed
//! by hand, in the same strict, line-numbered style as the `search-v1.tsv`
//! parser, because a cache line that silently parses wrong is a search index
//! that silently answers the wrong question.
//!
//! # The file format
//!
//! ```text
//! # comments and blank lines are ignored anywhere
//! orbweaver-vectors 1
//! IDL:gc20/Wallet:1.0<TAB>0.0131,-0.0442,0.9010
//! remaining funds in the account<TAB>0.0129,-0.0451,0.8998
//! ```
//!
//! A version header, then one entry per line: a key, a tab, and the vector as
//! comma-separated floats. Every entry must have the same dimension, keys are
//! unique, and every rejection names its line.
//!
//! Keys are deliberately untyped strings so that one file can hold both halves
//! of a search: **repository ids** for the catalog and **normalised query
//! text** (see [`query_key`]) for the queries. Search only ever consults keys
//! that name an exposed interface, so a query entry can never be returned as a
//! hit — the namespaces cannot collide in a way that matters.
//!
//! # Why the cache exists at all
//!
//! D003: vectors are cached in a versioned file next to the catalog so CI
//! replays do not re-bill the API and a first-pass run is reproducible. A
//! search path that called out to a network service per query would also make
//! `Bridge::search` fallible and slow, and it is neither today.

use std::collections::BTreeMap;

/// The format's first token. A file that does not begin with it is not ours.
pub const MAGIC: &str = "orbweaver-vectors";

/// The only format version this build reads.
///
/// Versioned from the first line on purpose: the vectors in a cache are only
/// comparable to each other when they came from the same model, and the day
/// that has to be recorded in the file is the day the field must already exist.
pub const FORMAT_VERSION: u32 = 1;

/// A cache of vectors, keyed by a stable string.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Vectors {
    dim: usize,
    entries: BTreeMap<String, Vec<f32>>,
}

impl Vectors {
    /// Builds a cache from key/vector pairs, refusing a ragged or empty one.
    ///
    /// The same invariants [`Vectors::parse`] enforces, so a cache built in
    /// memory and a cache read from disk cannot differ in what they promise.
    pub fn from_entries(
        entries: impl IntoIterator<Item = (String, Vec<f32>)>,
    ) -> Result<Vectors, String> {
        let mut map: BTreeMap<String, Vec<f32>> = BTreeMap::new();
        let mut dim = 0usize;
        for (key, vector) in entries {
            if key.is_empty() {
                return Err("empty key".to_owned());
            }
            if key.contains('\t') || key.contains('\n') {
                return Err(format!("key {key:?} contains a tab or newline"));
            }
            if vector.is_empty() {
                return Err(format!("key {key:?} has a zero-length vector"));
            }
            if dim == 0 {
                dim = vector.len();
            } else if vector.len() != dim {
                return Err(format!(
                    "key {key:?} has dimension {}, but the cache is {dim}-dimensional",
                    vector.len()
                ));
            }
            if map.insert(key.clone(), vector).is_some() {
                return Err(format!("duplicate key {key:?}"));
            }
        }
        Ok(Vectors { dim, entries: map })
    }

    /// Parses the cache format, refusing anything malformed **by line number**.
    ///
    /// Strict for the same reason the benchmark's TSV parser is: a vector cache
    /// is generated by a script and read by a search index, so nobody is
    /// looking at it when it goes wrong. The line number is what turns "the
    /// index is bad" into a one-second fix.
    pub fn parse(text: &str) -> Result<Vectors, String> {
        let mut entries: Vec<(String, Vec<f32>)> = Vec::new();
        let mut header_seen = false;
        let mut dim = 0usize;

        for (idx, raw) in text.lines().enumerate() {
            let line = idx + 1;
            let trimmed = raw.trim_end_matches(['\r']);
            if trimmed.trim().is_empty() || trimmed.trim_start().starts_with('#') {
                continue;
            }
            if !header_seen {
                let mut parts = trimmed.split_whitespace();
                let (Some(magic), Some(version), None) = (parts.next(), parts.next(), parts.next())
                else {
                    return Err(format!(
                        "line {line}: expected a header {MAGIC:?} <version>, got {trimmed:?}"
                    ));
                };
                if magic != MAGIC {
                    return Err(format!("line {line}: not a vector cache: {magic:?} != {MAGIC:?}"));
                }
                let Ok(version) = version.parse::<u32>() else {
                    return Err(format!("line {line}: version {version:?} is not a number"));
                };
                if version != FORMAT_VERSION {
                    return Err(format!(
                        "line {line}: format version {version} is not {FORMAT_VERSION}; \
                         regenerate the cache"
                    ));
                }
                header_seen = true;
                continue;
            }

            let fields: Vec<&str> = trimmed.split('\t').collect();
            let [key, floats] = fields.as_slice() else {
                return Err(format!(
                    "line {line}: expected key<TAB>floats, got {} tab-separated field(s)",
                    fields.len()
                ));
            };
            let key = key.trim();
            if key.is_empty() {
                return Err(format!("line {line}: empty key"));
            }
            let mut vector = Vec::new();
            for (n, piece) in floats.split(',').enumerate() {
                let piece = piece.trim();
                if piece.is_empty() {
                    return Err(format!("line {line}: component {} is empty", n + 1));
                }
                let Ok(value) = piece.parse::<f32>() else {
                    return Err(format!(
                        "line {line}: component {} is not a float: {piece:?}",
                        n + 1
                    ));
                };
                if !value.is_finite() {
                    return Err(format!("line {line}: component {} is not finite", n + 1));
                }
                vector.push(value);
            }
            if vector.is_empty() {
                return Err(format!("line {line}: no vector components"));
            }
            if dim == 0 {
                dim = vector.len();
            } else if vector.len() != dim {
                return Err(format!(
                    "line {line}: dimension {} does not match the file's {dim}",
                    vector.len()
                ));
            }
            entries.push((key.to_owned(), vector));
        }

        if !header_seen {
            return Err(format!("no {MAGIC:?} header; an unversioned cache is unreadable"));
        }
        Vectors::from_entries(entries)
    }

    /// Renders the cache back into the parse format, header and all.
    ///
    /// Round-trips: `Vectors::parse(&v.to_text()) == Ok(v)`, which is what lets
    /// a generator and this parser be tested against each other rather than
    /// against a fixture somebody typed.
    pub fn to_text(&self) -> String {
        let mut out = format!("{MAGIC} {FORMAT_VERSION}\n");
        for (key, vector) in &self.entries {
            out.push_str(key);
            out.push('\t');
            for (i, value) in vector.iter().enumerate() {
                if i > 0 {
                    out.push(',');
                }
                // Default Display is shortest-exact for floats, so the value
                // read back is the value written — a fixed precision here
                // would quietly break the round-trip promise above.
                out.push_str(&value.to_string());
            }
            out.push('\n');
        }
        out
    }

    /// The dimension every vector in the cache has. Zero for an empty cache.
    pub fn dim(&self) -> usize {
        self.dim
    }

    /// How many entries the cache holds.
    pub fn len(&self) -> usize {
        self.entries.len()
    }

    /// Whether the cache holds nothing.
    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// The vector stored under `key`, if any.
    pub fn get(&self, key: &str) -> Option<&[f32]> {
        self.entries.get(key).map(Vec::as_slice)
    }

    /// Every key, in sorted order.
    pub fn keys(&self) -> impl Iterator<Item = &str> {
        self.entries.keys().map(String::as_str)
    }
}

/// Cosine similarity, or `None` when the two vectors are not comparable.
///
/// `None` rather than a sentinel score: a dimension mismatch means the two
/// vectors came from different models, and any number returned for that pair
/// is a lie the ranking would then act on. A zero-norm vector is the same
/// situation — it has no direction to compare.
///
/// Accumulated in `f64` over `f32` storage: the cache is small and the
/// difference is free, and a ranking that flips on rounding is not
/// reproducible.
pub fn cosine(a: &[f32], b: &[f32]) -> Option<f64> {
    if a.len() != b.len() || a.is_empty() {
        return None;
    }
    let mut dot = 0f64;
    let mut na = 0f64;
    let mut nb = 0f64;
    for (x, y) in a.iter().zip(b) {
        let (x, y) = (f64::from(*x), f64::from(*y));
        dot += x * y;
        na += x * x;
        nb += y * y;
    }
    if na <= 0.0 || nb <= 0.0 {
        return None;
    }
    Some(dot / (na.sqrt() * nb.sqrt()))
}

/// One ranked key and the score that ranked it.
#[derive(Debug, Clone, PartialEq)]
pub struct Scored {
    /// The cache key — a repository id, for catalog entries.
    pub key: String,
    /// Cosine similarity against the query vector, in `[-1, 1]`.
    pub score: f64,
}

/// The `top_k` cache entries closest to `query`, best first.
///
/// Ties break on the key, ascending, so the output is a function of the input
/// and not of hash order — a benchmark that reorders between runs cannot be
/// used to judge a change. Entries whose dimension does not match `query` are
/// skipped rather than scored (see [`cosine`]).
pub fn rank(query: &[f32], vectors: &Vectors, top_k: usize) -> Vec<Scored> {
    let mut scored: Vec<Scored> = vectors
        .entries
        .iter()
        .filter_map(|(key, vector)| {
            cosine(query, vector).map(|score| Scored { key: key.clone(), score })
        })
        .collect();
    // `total_cmp` rather than `partial_cmp().unwrap()`: NaN cannot reach here
    // (cosine rejects zero norms and the parser rejects non-finite components),
    // and a sort that would panic if it ever did is a worse guarantee than one
    // that orders deterministically regardless.
    scored.sort_by(|a, b| b.score.total_cmp(&a.score).then_with(|| a.key.cmp(&b.key)));
    scored.truncate(top_k);
    scored
}

/// Why a search result surfaced.
///
/// Recorded per hit in the search document. An agent that cannot tell a
/// verbatim name match from a semantic neighbour cannot calibrate how much to
/// trust the list, and neither can the benchmark: a vector index that starts
/// answering the negative class is over-matching, and `via` is what makes that
/// visible instead of merely fatal.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Via {
    /// Matched the lexical haystack — a name or prose the author wrote.
    Lexical,
    /// Matched only by vector similarity above the threshold.
    Vector,
    /// Both paths found it.
    Both,
}

impl Via {
    /// The token written into the JSON.
    pub fn name(self) -> &'static str {
        match self {
            Via::Lexical => "lexical",
            Via::Vector => "vector",
            Via::Both => "both",
        }
    }
}

/// A vector index `Bridge::search` may consult, plus the cutoff it applies.
#[derive(Debug, Clone)]
pub struct VectorIndex {
    vectors: Vectors,
    threshold: f64,
}

impl VectorIndex {
    /// The default cosine cutoff for a vector-only hit.
    ///
    /// Chosen for the shape of a real sentence-embedding model, where unrelated
    /// text pairs cluster well below and paraphrases well above — not fitted to
    /// the frozen benchmark, which would be tuning the exam to the student
    /// (§8). It is `--threshold`-configurable precisely so that a different
    /// model can be calibrated without editing code, and the calibration is
    /// judged by the gates: **a threshold that lets the negative or injection
    /// class match anything is wrong, whatever it does for synonyms.**
    pub const DEFAULT_THRESHOLD: f64 = 0.60;

    /// An index over `vectors` at [`Self::DEFAULT_THRESHOLD`].
    pub fn new(vectors: Vectors) -> Self {
        Self { vectors, threshold: Self::DEFAULT_THRESHOLD }
    }

    /// The same index with a different cutoff.
    pub fn with_threshold(mut self, threshold: f64) -> Self {
        self.threshold = threshold;
        self
    }

    /// The cutoff a vector-only hit must reach.
    pub fn threshold(&self) -> f64 {
        self.threshold
    }

    /// The underlying cache.
    pub fn vectors(&self) -> &Vectors {
        &self.vectors
    }

    /// The vector for a query, if this cache was built with one.
    ///
    /// `None` is not an error and not a zero score: it means this query was
    /// never embedded, and the caller must report the query as **unmeasured**
    /// rather than as a vector miss (D003's absence rule — counted, named,
    /// never green).
    pub fn query_vector(&self, query: &str) -> Option<&[f32]> {
        self.vectors.get(&query_key(query))
    }

    /// Cosine between a query vector and the entry for `key`, if both exist.
    pub fn score(&self, query: &[f32], key: &str) -> Option<f64> {
        cosine(query, self.vectors.get(key)?)
    }
}

/// The cache key for a query string: trimmed, lowercased, whitespace runs
/// collapsed to one space.
///
/// Normalised so that the generator and the search path agree on spelling
/// without either having to know about the other, and collapsed so a key can
/// never contain the tab the file format uses as its separator — the format
/// cannot be broken by a query, only by an author.
pub fn query_key(query: &str) -> String {
    query.split_whitespace().collect::<Vec<&str>>().join(" ").to_lowercase()
}

#[cfg(test)]
mod tests {
    use super::*;

    const GOOD: &str = "# a cache\n\
                        orbweaver-vectors 1\n\
                        \n\
                        IDL:a/B:1.0\t1.0,0.0,0.0\n\
                        # mid-file comment\n\
                        IDL:c/D:1.0\t0.0,1.0,0.0\n\
                        remaining funds\t0.7071,0.7071,0.0\n";

    #[test]
    fn parses_the_shape_the_format_documents() {
        let v = Vectors::parse(GOOD).expect("parses");
        assert_eq!(v.len(), 3);
        assert_eq!(v.dim(), 3);
        assert_eq!(v.get("IDL:a/B:1.0"), Some([1.0f32, 0.0, 0.0].as_slice()));
        assert_eq!(v.get("nope"), None);
        assert_eq!(v.keys().count(), 3);
    }

    /// Every rejection carries the line number, or a 4000-line cache becomes a
    /// hunt — the same rule the benchmark's TSV parser lives by.
    #[test]
    fn rejects_malformed_lines_by_number() {
        for (src, needle, why) in [
            ("orbweaver-vectors 1\nIDL:a/B:1.0\n", "line 2", "no tab"),
            ("orbweaver-vectors 1\nIDL:a/B:1.0\t1.0\t2.0\n", "line 2", "two tabs"),
            ("orbweaver-vectors 1\n\t1.0\n", "line 2", "empty key"),
            ("orbweaver-vectors 1\nk\t1.0,,2.0\n", "line 2", "empty component"),
            ("orbweaver-vectors 1\nk\t1.0,two\n", "line 2", "non-float component"),
            ("orbweaver-vectors 1\nk\tinf\n", "line 2", "non-finite component"),
            ("orbweaver-vectors 1\na\t1,2\nb\t1,2,3\n", "line 3", "ragged dimension"),
            ("orbweaver-vectors 2\na\t1,2\n", "line 1", "wrong version"),
            ("vectors 1\na\t1,2\n", "line 1", "wrong magic"),
            ("orbweaver-vectors x\na\t1,2\n", "line 1", "non-numeric version"),
            ("orbweaver-vectors\na\t1,2\n", "line 1", "header missing the version"),
        ] {
            let err = Vectors::parse(src).expect_err(why);
            assert!(err.contains(needle), "{why}: {err:?} does not name {needle}");
        }
        // A headerless file is rejected as a whole, not per line: there is no
        // line to blame when the version everything depends on is simply absent.
        let err = Vectors::parse("# nothing but comments\n").expect_err("no header");
        assert!(err.contains("header"), "{err:?}");
        // Duplicates are a generator bug, and silently keeping the last one
        // would make the index depend on file order.
        let err = Vectors::parse("orbweaver-vectors 1\na\t1,2\na\t3,4\n").expect_err("duplicate");
        assert!(err.contains("duplicate"), "{err:?}");
    }

    #[test]
    fn text_round_trips_through_the_parser() {
        let v = Vectors::parse(GOOD).expect("parses");
        let again = Vectors::parse(&v.to_text()).expect("re-parses");
        assert_eq!(v, again);
        assert!(v.to_text().starts_with("orbweaver-vectors 1\n"));
    }

    #[test]
    fn cosine_refuses_what_it_cannot_compare() {
        assert_eq!(cosine(&[1.0, 0.0], &[1.0, 0.0]), Some(1.0));
        assert_eq!(cosine(&[1.0, 0.0], &[-1.0, 0.0]), Some(-1.0));
        assert_eq!(cosine(&[1.0, 0.0], &[0.0, 1.0]), Some(0.0));
        // Different models, no comparable answer.
        assert_eq!(cosine(&[1.0, 0.0], &[1.0, 0.0, 0.0]), None);
        // No direction to compare.
        assert_eq!(cosine(&[0.0, 0.0], &[1.0, 0.0]), None);
        assert_eq!(cosine(&[], &[]), None);
    }

    #[test]
    fn rank_is_ordered_and_deterministic() {
        let v = Vectors::parse(GOOD).expect("parses");
        let out = rank(&[1.0, 0.0, 0.0], &v, 2);
        assert_eq!(out.len(), 2);
        assert_eq!(out[0].key, "IDL:a/B:1.0");
        assert!((out[0].score - 1.0).abs() < 1e-9);
        assert_eq!(out[1].key, "remaining funds");
        // Every tied key orders by name, so two runs agree.
        let tied = Vectors::from_entries([
            ("zeta".to_owned(), vec![1.0, 0.0]),
            ("alpha".to_owned(), vec![1.0, 0.0]),
        ])
        .expect("builds");
        let out = rank(&[1.0, 0.0], &tied, 8);
        assert_eq!(out.iter().map(|s| s.key.as_str()).collect::<Vec<_>>(), ["alpha", "zeta"]);
    }

    /// A query embedded under one model against a catalog embedded under
    /// another must score nothing at all, not a plausible-looking number.
    #[test]
    fn a_dimension_mismatch_is_skipped_not_scored() {
        let v = Vectors::parse(GOOD).expect("parses");
        assert!(rank(&[1.0, 0.0], &v, 8).is_empty());
        let ix = VectorIndex::new(v);
        assert_eq!(ix.score(&[1.0, 0.0], "IDL:a/B:1.0"), None);
    }

    #[test]
    fn query_keys_normalise_the_spelling_both_sides_use() {
        assert_eq!(
            query_key("  Remaining   FUNDS\tin the account "),
            "remaining funds in the account"
        );
        assert!(!query_key("a\tb").contains('\t'));
        let v = Vectors::parse(GOOD).expect("parses");
        let ix = VectorIndex::new(v);
        assert!(ix.query_vector("  Remaining  Funds ").is_some());
        assert!(ix.query_vector("never embedded").is_none());
    }

    #[test]
    fn from_entries_enforces_the_same_invariants_as_the_parser() {
        assert!(
            Vectors::from_entries([("a".to_owned(), vec![1.0]), ("a".to_owned(), vec![2.0])])
                .is_err()
        );
        assert!(
            Vectors::from_entries([("a".to_owned(), vec![1.0]), ("b".to_owned(), vec![1.0, 2.0])])
                .is_err()
        );
        assert!(Vectors::from_entries([("a\tb".to_owned(), vec![1.0])]).is_err());
        assert!(Vectors::from_entries([(String::new(), vec![1.0])]).is_err());
        assert!(Vectors::from_entries([("a".to_owned(), vec![])]).is_err());
        let empty = Vectors::from_entries([]).expect("an empty cache is legal");
        assert!(empty.is_empty());
        assert_eq!(empty.dim(), 0);
    }

    #[test]
    fn the_threshold_is_a_knob_with_a_documented_default() {
        let ix = VectorIndex::new(Vectors::default());
        assert!((ix.threshold() - VectorIndex::DEFAULT_THRESHOLD).abs() < f64::EPSILON);
        assert!((ix.with_threshold(0.9).threshold() - 0.9).abs() < f64::EPSILON);
    }

    #[test]
    fn via_names_are_the_tokens_the_document_promises() {
        assert_eq!(Via::Lexical.name(), "lexical");
        assert_eq!(Via::Vector.name(), "vector");
        assert_eq!(Via::Both.name(), "both");
    }
}
