//! omniORB's own `LOCATION_FORWARD` replies, octet for octet, decoded by us.
//!
//! `crates/orbweaver-giop/tests/foreign_forward.rs` measures the live thing: a
//! foreign ORB forwards our client and our client lands at the other process.
//! It needs two omniORB processes, so it is `#[ignore]`d and only
//! `spikes/foreign_forward.sh` runs it.
//!
//! This file is what remains true when omniORB is not installed. It holds three
//! replies omniORB actually wrote and asserts our decoder reads them — so the
//! foreign-forward claim has a gate inside `cargo test --workspace`, which runs
//! for everybody, rather than only inside a script somebody remembers to run.
//! That is the same argument the corpus differential settled on when eight
//! files had landed without either front end comparing them: *a prohibition
//! without its replacement is an instruction to skip the check*, and a gate
//! that only fires where the fixture is installed is a gate most readers never
//! fire at all.
//!
//! # Provenance
//!
//! Captured 2026-08-26 by `spikes/foreign_forward_capture.py --hexdump` from
//! **omniORB 4.3.4** (Homebrew, macOS 25.6.0, arm64), driven by
//! `spikes/foreign_forward_peer.py --role forward`, whose POA raises
//! `PortableServer.ForwardRequest` from a `ServantLocator`. The forwarder sat
//! at `127.0.0.1:54312`; the destination it names in every one of these three
//! replies is `127.0.0.1:54310`. Both are ephemeral ports of that run — see
//! *What is not asserted* below.
//!
//! The request that produced each was `where_am_i(in string)` sent
//! **little-endian** at the version named. Nothing in this repository encoded
//! any of these octets.
//!
//! # Re-taken, not frozen
//!
//! A recording is worth what it still describes. `spikes/foreign_forward.sh`
//! re-takes the reply from the live fixture on every run and
//! `foreign_forward_capture.py --check-recording` compares the **decoded
//! values** here against what the live peer writes today. CLAUDE.md's rule
//! against comparing raw buffers is the reason the comparison is on decoded
//! fields; the reason it is not on *all* of them is below.
//!
//! # What is not asserted, and why
//!
//! The forwarded-to **port** and **object key** are regenerated by the fixture
//! on every run — the ports are ephemeral by design, so that a concurrent
//! harness cannot collide with this leg. Asserting them would produce a test
//! that is red on every machine but the one that recorded it, which is the
//! same defect as asserting padding content: pinning a byte the specification
//! (or, here, the fixture) does not fix. What is asserted is everything that
//! *is* stable — the reply status, the GIOP version, the repository id, the
//! profile's IIOP version, the profile count, and the loopback host.
//!
//! # The one thing these three recordings prove that a live run does not
//!
//! GIOP 1.0 and 1.1 put the service-context list *before* the request id and
//! status; 1.2 puts it after, and pads the body to an 8-boundary from the start
//! of the message. Those three layouts are visible here as three different
//! octet strings for one logical answer — the 1.0 and 1.1 recordings differ in
//! exactly one octet (the minor version) and the 1.2 one differs in the first
//! sixteen. A decoder that had the 1.2 layout wired in for all three would pass
//! a live run against a peer that happened to speak 1.2 and fail here.

use orbweaver_giop::{Ior, ReplyStatus, decode_reply, read_message};

/// omniORB 4.3.4's `LOCATION_FORWARD` reply to a GIOP **1.0** request.
const FORWARD_1_0: &str = concat!(
    "47494f5001000101a00000000000000057510000030000002100000049444c3a",
    "666f726569676e5f666f72776172642f576179706f696e743a312e3000000000",
    "010000000000000060000000010102000a0000003132372e302e302e310026d4",
    "0e000000fe80ae8e6a00007c4300000000000000020000000000000008000000",
    "0100000000545441010000001c00000001000000010001000100000001000105",
    "090101000100000009010100",
);

/// The same answer at GIOP **1.1**. One octet different from 1.0: the minor.
const FORWARD_1_1: &str = concat!(
    "47494f5001010101a00000000000000057510000030000002100000049444c3a",
    "666f726569676e5f666f72776172642f576179706f696e743a312e3000000000",
    "010000000000000060000000010102000a0000003132372e302e302e310026d4",
    "0e000000fe80ae8e6a00007c4300000000000000020000000000000008000000",
    "0100000000545441010000001c00000001000000010001000100000001000105",
    "090101000100000009010100",
);

/// The same answer at GIOP **1.2**, whose reply header is laid out differently.
const FORWARD_1_2: &str = concat!(
    "47494f5001020101a00000005751000003000000000000002100000049444c3a",
    "666f726569676e5f666f72776172642f576179706f696e743a312e3000000000",
    "010000000000000060000000010102000a0000003132372e302e302e310026d4",
    "0e000000fe80ae8e6a00007c4300000000000000020000000000000008000000",
    "0100000000545441010000001c00000001000000010001000100000001000105",
    "090101000100000009010100",
);

/// The repository id the forwarded-to reference carries, from `spikes/foreign_forward.idl`.
const REPO_ID: &str = "IDL:foreign_forward/Waypoint:1.0";

/// The host every recording names. Stable; the port beside it is not.
const HOST: &str = "127.0.0.1";

fn octets(hex: &str) -> Vec<u8> {
    assert!(hex.len().is_multiple_of(2), "a recording must be whole octets");
    (0..hex.len() / 2)
        .map(|i| u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).expect("recording is not hex"))
        .collect()
}

/// Decode one recording the way a client reading a socket would.
fn decode(hex: &str) -> (orbweaver_giop::Reply, Ior) {
    let raw = octets(hex);
    let msg = read_message(&mut raw.as_slice(), 64 * 1024)
        .expect("omniORB's reply is not a readable GIOP message");
    let reply = decode_reply(msg).expect("omniORB's reply does not decode");
    let ior = {
        let mut body = reply.body().expect("LOCATION_FORWARD carries a body");
        Ior::read_from(&mut body).expect("the forwarded-to IOR does not decode")
    };
    (reply, ior)
}

/// The shared assertions: this is a forward, and it names a callable target.
fn assert_is_a_foreign_forward(hex: &str, minor: u8) {
    let (reply, ior) = decode(hex);

    assert_eq!(
        reply.status,
        ReplyStatus::LocationForward,
        "GIOP 1.{minor}: omniORB's recorded reply does not read as a forward"
    );
    assert_eq!(reply.version.major, 1, "GIOP 1.{minor}: major version");
    assert_eq!(reply.version.minor, minor, "GIOP 1.{minor}: the reply's own version octet");

    assert_eq!(
        ior.type_id, REPO_ID,
        "GIOP 1.{minor}: the forwarded-to reference names a different interface"
    );

    let p =
        ior.primary().unwrap_or_else(|e| panic!("GIOP 1.{minor}: no IIOP profile to dial: {e}"));
    assert_eq!(p.host, HOST, "GIOP 1.{minor}: forwarded-to host");
    assert_ne!(p.port, 0, "GIOP 1.{minor}: a forward to port 0 is not a callable target");
    // The profile's own version, which is independent of the reply's: omniORB
    // published 1.2 profiles while answering a 1.0 request, and a client that
    // assumed the two agreed would dial with the wrong header layout.
    assert_eq!(
        (p.version.major, p.version.minor),
        (1, 2),
        "GIOP 1.{minor}: the forwarded-to IIOP profile's version"
    );
    assert_eq!(ior.profiles.len(), 1, "GIOP 1.{minor}: profile count in the recording");
    assert!(!p.object_key.is_empty(), "GIOP 1.{minor}: forwarded-to profile carries no object key");
}

#[test]
fn omniorb_1_0_location_forward_decodes() {
    assert_is_a_foreign_forward(FORWARD_1_0, 0);
}

#[test]
fn omniorb_1_1_location_forward_decodes() {
    assert_is_a_foreign_forward(FORWARD_1_1, 1);
}

#[test]
fn omniorb_1_2_location_forward_decodes() {
    assert_is_a_foreign_forward(FORWARD_1_2, 2);
}

/// All three recordings name the **same** destination.
///
/// They were taken in one run against one pair of processes, so a decoder that
/// read the address out of the wrong offset for one version would show up here
/// as three answers where there should be one — a cross-check the three tests
/// above cannot make individually, because each of them would happily agree
/// with itself.
#[test]
fn the_three_versions_name_one_destination() {
    let addrs: Vec<(String, u16)> = [FORWARD_1_0, FORWARD_1_1, FORWARD_1_2]
        .iter()
        .map(|h| {
            let (_, ior) = decode(h);
            let p = ior.primary().expect("profile");
            (p.host.clone(), p.port)
        })
        .collect();
    assert_eq!(
        addrs[0], addrs[1],
        "GIOP 1.0 and 1.1 recordings disagree about where they forward to"
    );
    assert_eq!(
        addrs[1], addrs[2],
        "GIOP 1.1 and 1.2 recordings disagree about where they forward to"
    );
}

/// The 1.0 and 1.1 recordings differ in exactly one octet, and it is the minor.
///
/// This is an assertion about the *recordings*, not about the protocol, and it
/// is here because it is the cheapest way to catch a recording that was pasted
/// over the wrong constant — the failure mode where two of these three tests
/// pass while measuring the same bytes twice.
#[test]
fn the_1_0_and_1_1_recordings_differ_only_in_the_version_octet() {
    let a = octets(FORWARD_1_0);
    let b = octets(FORWARD_1_1);
    let differ: Vec<usize> =
        a.iter().zip(b.iter()).enumerate().filter(|(_, (x, y))| x != y).map(|(i, _)| i).collect();
    assert_eq!(
        differ,
        vec![5],
        "the 1.0 and 1.1 recordings should differ at offset 5 (the GIOP minor \
         version) and nowhere else"
    );
    assert_eq!((a[5], b[5]), (0, 1), "the octet at 5 is the minor version");
}
