#!/usr/bin/env python3
"""Render `service_sweep.sh --raw` into the tables `docs/SERVICES-COVERAGE.md`
§8 carries — so the document is generated from the measurement, never
transcribed from it.

    ./spikes/service_sweep.sh --raw | python3 spikes/coverage_tables.py
    python3 spikes/coverage_tables.py --check < sweep.tsv   # diff against the doc

`--check` extracts the region between the BEGIN/END markers in the document
and exits 1 with a unified diff when the committed tables no longer say what
the wire says. That is the harness's oracle for the document, the same move
`records_keep_up.py` made one level up: a script cannot check a sentence for
truth, so the tables that *can* be checked are the ones the script writes.

The renderer is deterministic — rows keep the sweep's order, which is the IDL
declaration order — and it renders nothing it did not read: an interface no
object claimed is listed as the sweep reports it, a `MARSHAL` is written as
`MARSHAL` (dispatch proven, correctness not), and pseudo-operations from
`CORBA::Object` are counted apart. Both languages of the heading are one line,
because a generated block that only one language could read would be a fact
with two homes.
"""
import difflib
import sys
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOC = ROOT / "docs/SERVICES-COVERAGE.md"
BEGIN = "<!-- BEGIN generated by spikes/coverage_tables.py from service_sweep.sh --raw; edit the sweep, not this block -->"
END = "<!-- END generated -->"
PSEUDO = "IDL:omg.org/CORBA/Object:1.0"

KIND_LABEL = {
    "dispatched": "served",
    "deferred": "deferred (`NO_IMPLEMENT`)",
    "refused": "refused (`NO_PERMISSION`)",
    "not-dispatched": "not dispatched (`BAD_OPERATION`)",
    "unmeasured": "unmeasured",
}


def parse(text):
    services = OrderedDict()   # service -> {"rows": [...], "total": {...}}
    unserved = []
    unprobed = []
    for line in text.splitlines():
        parts = line.rstrip("\n").split("\t")
        tag = parts[0]
        if tag == "ROW" and len(parts) == 7:
            _, service, obj, iface, op, answer, kind = parts
            services.setdefault(service, {"rows": [], "total": None})
            services[service]["rows"].append((obj, iface, op, answer, kind))
        elif tag == "TOTAL" and len(parts) >= 3:
            service = parts[1]
            services.setdefault(service, {"rows": [], "total": None})
            tot = OrderedDict()
            for cell in parts[2:]:
                k, _, v = cell.rpartition(" ")
                tot[k] = int(v)
            services[service]["total"] = tot
        elif tag == "UNSERVED" and len(parts) >= 4:
            unserved.append((parts[1], parts[2], parts[3]))
        elif tag == "UNPROBED" and len(parts) >= 4:
            unprobed.append((parts[1], parts[2], parts[3]))
    return services, unserved, unprobed


def cell(s):
    return s.replace("|", "\\|")


def render(text):
    services, unserved, unprobed = parse(text)
    out = [BEGIN, ""]
    if not services:
        out += ["_The sweep produced no rows — an unmeasured document, not an empty service._", "", END]
        return "\n".join(out) + "\n"

    # ── per-service tables ────────────────────────────────────────────────
    for service, data in services.items():
        rows = data["rows"]
        declared = OrderedDict()   # (iface, op) -> [(obj, answer, kind)]
        for obj, iface, op, answer, kind in rows:
            declared.setdefault((iface, op), []).append((obj, answer, kind))
        real = [k for k in declared if k[0] != PSEUDO]
        pseudo = [k for k in declared if k[0] == PSEUDO]
        served = sum(1 for k in real if any(kd == "dispatched" for _, _, kd in declared[k]))
        out.append("### %s — %d declared, %d served / 선언 %d, 서빙 %d"
                   % (service, len(real), served, len(real), served))
        out.append("")
        out.append("| Interface | Operation | Answer, per object probed | Class |")
        out.append("|---|---|---|---|")
        for iface, op in real:
            probes = declared[(iface, op)]
            answers = "; ".join("%s → `%s`" % (cell(o), cell(a)) for o, a, _ in probes)
            kinds = []
            for _, _, kd in probes:
                lbl = KIND_LABEL.get(kd, kd)
                if lbl not in kinds:
                    kinds.append(lbl)
            out.append("| `%s` | `%s` | %s | %s |" % (cell(iface), cell(op), answers, ", ".join(kinds)))
        if pseudo:
            names = ", ".join("`%s`" % op for _, op in pseudo)
            out.append("")
            out.append("_`CORBA::Object` pseudo-operations probed and counted apart: %s._" % names)
        out.append("")

    # ── totals ────────────────────────────────────────────────────────────
    out.append("### Totals / 합계")
    out.append("")
    out.append("| Service | Declared | Served | Deferred `NO_IMPLEMENT` | Refused `NO_PERMISSION` | Not dispatched `BAD_OPERATION` | Probes | Unmeasured |")
    out.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    sums = [0] * 7
    for service, data in services.items():
        rows = data["rows"]
        declared = OrderedDict()
        for obj, iface, op, answer, kind in rows:
            if iface != PSEUDO:
                declared.setdefault((iface, op), []).append(kind)
        n_decl = len(declared)
        n_served = sum(1 for kinds in declared.values() if "dispatched" in kinds)
        n_def = sum(1 for kinds in declared.values() if "dispatched" not in kinds and "deferred" in kinds)
        n_ref = sum(1 for kinds in declared.values() if "dispatched" not in kinds and "deferred" not in kinds and "refused" in kinds)
        n_bad = sum(1 for kinds in declared.values() if set(kinds) == {"not-dispatched"})
        tot = data["total"] or {}
        n_probes = tot.get("probes", len(rows))
        n_unm = tot.get("unmeasured", 0)
        vals = [n_decl, n_served, n_def, n_ref, n_bad, n_probes, n_unm]
        sums = [a + b for a, b in zip(sums, vals)]
        out.append("| %s | %d | %d | %d | %d | %d | %d | %d |" % ((service,) + tuple(vals)))
    out.append("| **total** | **%d** | **%d** | **%d** | **%d** | **%d** | **%d** | **%d** |" % tuple(sums))
    out.append("")
    out.append("_Declared_ counts each `interface::operation` once however many objects it was probed on; "
               "an operation is _served_ if any object dispatched it. `MARSHAL` on a 64-zero-byte probe "
               "proves dispatch, not correctness (§9). / _선언_은 객체 수와 무관하게 `인터페이스::연산`을 한 번씩 센다.")
    out.append("")

    # ── unserved interfaces ───────────────────────────────────────────────
    out.append("### Interfaces no object claimed / 어떤 객체도 주장하지 않는 인터페이스")
    out.append("")
    if unserved:
        out.append("| Service | Interface | Reported |")
        out.append("|---|---|---|")
        for service, iface, why in unserved:
            out.append("| %s | `%s` | %s |" % (service, cell(iface), cell(why)))
    else:
        out.append("_none_")
    out.append("")

    # ── declared, probed against nothing — unmeasured, not passing ─────────
    out.append("### Declared, probed against no object — unmeasured / 선언되었으나 프로브한 객체 없음 — 미측정")
    out.append("")
    if unprobed:
        by_service = OrderedDict()
        for service, iface, why in unprobed:
            by_service.setdefault(service, []).append("`%s` (%s)" % (cell(iface), cell(why.split(",")[0])))
        for service, items in by_service.items():
            out.append("- **%s** — %d interface(s): %s" % (service, len(items), ", ".join(items)))
    else:
        out.append("_none_")
    out.append("")
    out.append(END)
    return "\n".join(out) + "\n"


def region_of(doc_text):
    b = doc_text.find(BEGIN)
    e = doc_text.find(END)
    if b < 0 or e < 0 or e < b:
        return None
    return doc_text[b:e + len(END)] + "\n"


def main(argv):
    text = sys.stdin.read()
    rendered = render(text)
    if "--check" not in argv:
        sys.stdout.write(rendered)
        return 0
    doc = DOC.read_text()
    committed = region_of(doc)
    if committed is None:
        print("  FAIL %s has no generated region (%s … %s)" % (DOC.name, BEGIN[:20], END))
        return 1
    if committed == rendered:
        n = sum(1 for l in rendered.splitlines() if l.startswith("| ") and not l.startswith("| Service") and not l.startswith("| Interface"))
        print("  ok   docs/SERVICES-COVERAGE.md §8 says what the wire says (%d table row(s))" % n)
        return 0
    print("  FAIL docs/SERVICES-COVERAGE.md §8 no longer says what the wire says; regenerate:")
    print("       ./spikes/service_sweep.sh --raw | python3 spikes/coverage_tables.py --write")
    for line in difflib.unified_diff(committed.splitlines(), rendered.splitlines(),
                                     "committed", "measured", lineterm="", n=0):
        print("       " + line)
    return 1


def write(argv):
    text = sys.stdin.read()
    rendered = render(text)
    doc = DOC.read_text()
    committed = region_of(doc)
    if committed is None:
        print("no generated region in %s" % DOC)
        return 1
    DOC.write_text(doc.replace(committed, rendered))
    print("wrote %s" % DOC)
    return 0


if __name__ == "__main__":
    if "--write" in sys.argv:
        sys.exit(write(sys.argv))
    sys.exit(main(sys.argv))
