#!/usr/bin/env python3
"""The SSL twin of `echo_server.py`: the same Echo servant over omniORB's sslTP.

This is a TEST FIXTURE. omniORB and omniORBpy are LGPL/GPL and are never linked
into or shipped with Orbweaver — the Rust client talks to it over the wire only,
using the published GIOP and SSLIOP specifications. See CLAUDE.md's licensing
boundary.

What it is for, and what it is NOT for. `spikes/ssliop.sh` already proves SSLIOP
peer interop (21 of 21, 2026-08-25) against a peer that imports no ORB, because
SSLIOP is unmodified GIOP over TLS plus one component. What that peer cannot do
is produce a `TAG_SSL_SEC_TRANS` component from **another ORB's own encoder** —
a claim about their encoder that only they can make. That is this fixture's one
job: publish an IOR omniORB wrote, so `spike-dump` can read the component off
bytes this project did not produce.

`spikes/tls/PEER-STATUS.md` specified this file on 2026-08-13 and recorded why it
could not run: Homebrew's omniORBpy is built without `sslTP`. It runs since
2026-09-03 under an omniORBpy built from source against the brew keg
(`spikes/tls/setup.sh`), into a directory this repository ignores. The credential
API was READ off the built module rather than guessed, as that document insists:
this version wants `key_file` with the chain and key in one PEM.

Differs from `echo_server.py` only in transport setup, all before `ORB_init`.

*`echo_server.py`의 SSL 쌍둥이. 피어 상호운용은 이미 21/21로 증명되어 있고, 이
픽스처의 유일한 일은 **다른 ORB의 인코더가 만든** `TAG_SSL_SEC_TRANS`를 발행하는
것이다. 2026-08-13에 명세되고 막혔던 것이 2026-09-03에 돈다 — 소스 빌드한
omniORBpy 아래에서, 자격증명 API는 추측이 아니라 빌드된 모듈에서 읽었다.*
"""
import pathlib
import sys

from omniORB import CORBA, sslTP
import omniORB

HERE = pathlib.Path(__file__).parent
TLS = HERE / "tls"

# ── transport, before ORB_init ──────────────────────────────────────────────
#
# One PEM holding chain then key: what THIS build's `key_file` reads. Written to
# a scratch path beside the fixtures rather than committed, because the
# concatenation is derived and `regen.sh` owns the originals.
bundle = TLS / ".server-bundle.pem"
bundle.write_text((TLS / "server.pem").read_text() + (TLS / "server.key").read_text())
# What this server TRUSTS: its own CA, plus the self-signed client identity.
# omniORB requires a client certificate (it publishes ESTABLISH_TRUST_IN_CLIENT
# in `target_requires` and this build's `sslTP` exposes no way to relax that),
# and `tls/client.pem` is self-signed rather than CA-issued on purpose —
# `regen.sh` deletes the CA keys so nothing can ever be signed again, and that
# decision is kept rather than worked around. Derived, like the bundle above.
trust = TLS / ".server-trust.pem"
trust.write_text((TLS / "ca.pem").read_text() + (TLS / "client.pem").read_text())
sslTP.certificate_authority_file(str(trust))
sslTP.key_file(str(bundle))
sslTP.key_file_password("")

omniORB.importIDL(str(HERE / "echo.idl"))
import spike, spike__POA  # noqa: E402  (generated by importIDL)
from orbexit import leave  # noqa: E402


class Echo(spike__POA.Echo):
    def ping(self):
        return 42

    def add(self, a, b):
        return a + b

    def echo_string(self, msg):
        return msg

    def scale(self, v, by):
        return v * by

    def echo_ragged(self, v):
        return v

    def echo_any(self, v):
        return v

    def blob(self, size):
        return bytes((i % 251) for i in range(size))

    def echo_wstring(self, w):
        return w

    def get_self(self):
        return self._this()

    def same_as(self, other):
        return self._this()._is_equivalent(other)

    def blob_sum(self, b):
        return sum(b) % 2147483647


def main():
    # `giop:ssl:127.0.0.1:0` — an SSL endpoint on loopback, ephemeral port, so
    # the published profile carries TAG_SSL_SEC_TRANS and no fixed port can
    # collide. **Loopback by name, not by default**: left unspecified, omniORB
    # publishes the host's LAN address, and the first dial of this fixture was
    # refused with `certificate not valid for name "172.30.1.49"` — the right
    # refusal, since `tls/server.pem` is issued for localhost/127.0.0.1, and a
    # measurement that verification is on and effective. Kept as a note rather
    # than a case, because it measures the fixture's address and not the peer.
    argv = sys.argv + ["-ORBendPoint", "giop:ssl:127.0.0.1:0"]
    orb = CORBA.ORB_init(argv, CORBA.ORB_ID)
    poa = orb.resolve_initial_references("RootPOA")
    servant = Echo()
    ref = servant._this()
    poa._get_the_POAManager().activate()

    ior = orb.object_to_string(ref)
    out = HERE / "echo_ssl.ior"
    out.write_text(ior)
    print(f"IOR written to {out}", flush=True)
    print("READY", flush=True)
    try:
        orb.run()
    except KeyboardInterrupt:
        orb.shutdown(True)


if __name__ == "__main__":
    leave(main())
