#!/usr/bin/env python3
"""Stock omniORB server used as the interop peer for Phase 0 assumption A.

This is a TEST FIXTURE. omniORB is LGPL/GPL and is never linked into or
shipped with Orbweaver — the Rust client talks to it over the wire only,
using the published GIOP specification. See docs/PLAN.md section 10.
"""
import sys, os, pathlib
from omniORB import CORBA, PortableServer
import omniORB

HERE = pathlib.Path(__file__).parent
omniORB.importIDL(str(HERE / "echo.idl"))
import spike, spike__POA  # noqa: E402  (generated by importIDL)


class Echo(spike__POA.Echo):
    def ping(self):
        return 42

    def add(self, a, b):
        return a + b

    def echo_string(self, msg):
        return msg

    def scale(self, v, by):
        return v * by

    def echo_ragged(self, v):
        return v

    def echo_any(self, v):
        return v


def main():
    orb = CORBA.ORB_init(sys.argv, CORBA.ORB_ID)
    poa = orb.resolve_initial_references("RootPOA")
    servant = Echo()
    ref = servant._this()
    poa._get_the_POAManager().activate()

    ior = orb.object_to_string(ref)
    out = HERE / "echo.ior"
    out.write_text(ior)
    print(f"IOR written to {out}", flush=True)
    print("READY", flush=True)
    try:
        orb.run()
    except KeyboardInterrupt:
        orb.shutdown(True)


if __name__ == "__main__":
    main()
