#!/usr/bin/env python3
"""Stock omniORB peer for the contract-evolution check.

This is a TEST FIXTURE. omniORB is LGPL/GPL and is never linked into or
shipped with Orbweaver — the Rust client talks to it over the wire only,
using the published GIOP specification. See docs/PLAN.md section 10.

Two states of one deployed service:

  (default)  built from evolution_v1.idl  — the version in production
  --updated  built from evolution_v1b.idl — the same service after an
             additive-only release, so it also answers `total`

Both keep the v1 Point layout. The point of the check is what happens when a
*client* is built from a contract whose struct disagrees, so the server must
not move.
"""
import sys, pathlib
from omniORB import CORBA, PortableServer
import omniORB

HERE = pathlib.Path(__file__).parent
UPDATED = "--updated" in sys.argv
omniORB.importIDL(str(HERE / ("evolution_v1b.idl" if UPDATED else "evolution_v1.idl")))
import evo, evo__POA  # noqa: E402  (generated by importIDL)


class Reader(evo__POA.Reader):
    # Deliberately not "return p.px": naming the member is the whole question.
    # These read whichever member the *server's* IDL declared first and second,
    # which is what a real servant compiled from the deployed contract does.
    def first(self, p):
        return p.px

    def second(self, p):
        return p.py

    if UPDATED:
        def total(self, p):
            return p.px + p.py


def main():
    argv = [a for a in sys.argv if a != "--updated"]
    orb = CORBA.ORB_init(argv, CORBA.ORB_ID)
    poa = orb.resolve_initial_references("RootPOA")
    ref = Reader()._this()
    poa._get_the_POAManager().activate()

    (HERE / "evolution.ior").write_text(orb.object_to_string(ref))
    orb.run()


if __name__ == "__main__":
    main()
