#!/usr/bin/env bash
# Container probe for risk R7: a client in another routing domain.
#
# ***THIS SCRIPT HAS NEVER BEEN RUN.***
#
# It was written on a machine with no Docker (`docker: command not found`), so
# nothing below is evidence of anything. `spikes/nat_rewrite.sh` counts it as a
# SKIP, never a pass, and the first person to run it should expect to fix it
# rather than to confirm it. What it is for is stated so that fixing it is
# cheap: the single thing this probe adds over the host-only measurement is a
# client that genuinely cannot route to the servant's own address.
#
#   ./spikes/nat/preflight.sh    # whether this machine can run it, and what is
#                                # missing if not — measured, not asserted
#   ./spikes/nat/run.sh
#
# Its sibling `spikes/nat/k8s/` is the same assertion against a Deployment
# behind a Service, dialed from outside the cluster. That one also translates
# the *port* (a NodePort is not the port the servant bound), which this one
# does not; it is equally unrun.
#
# Expected outcome, which is the assertion:
#   naive      the servant publishes its container address; the client's dial
#              FAILS (it hangs to the connect timeout, then errors)
#   published  the servant publishes host.docker.internal:5555; the client's
#              dial SUCCEEDS and ping() returns 42
#
# A run where both succeed has not demonstrated the fix — it has demonstrated
# that the two networks are not isolated, which is a broken probe, not a pass.
set -uo pipefail
cd "$(dirname "$0")"
ROOT=$(cd ../.. && pwd)

fails=0
DC="docker compose -f compose.yaml"

cleanup() { $DC down -v --remove-orphans >/dev/null 2>&1; }
trap cleanup EXIT

# A refusal is not a failure and not a pass: the probe did not run, and the
# sentence says why. Exit 2, distinct from 1 (ran, did not demonstrate the fix)
# and 0 (ran, did).
refuse() {
  echo "  UNMEASURED $1"
  exit 2
}

# ── derive_dockerignore begin ────────────────────────────────────────────────
# The build context is the repository root, and a context that ships `target/`
# — gigabytes a `cargo test --workspace` has just written — is wrong at any
# size, whatever it costs. What must not enter the context is exactly what
# `.gitignore` already says is not the tree, so the ignore file for docker is
# DERIVED from it here, on every run, and never typed twice: the committed
# `.dockerignore` is this function's output, and `local_checks.sh` fails the
# moment the two differ. `local_checks.sh` lifts this function out of this file
# by the two marker lines that fence it — move them and it lifts nothing, which
# it refuses rather than passing over.
#
# The translation, because the two matchers differ and a pattern copied
# verbatim would mean something else:
#   - a trailing `/` (git: directories only) is dropped — docker's matcher
#     has no directory-only form, so a FILE named `build` would also be
#     excluded, which nothing this probe copies is;
#   - a pattern with no `/` matches at any depth in git; docker anchors every
#     pattern at the context root, so it becomes `**/name`;
#   - a pattern with a `/` is anchored in both, and a leading `/` is dropped;
#   - `!` negations carry over, and order carries over with them: both
#     matchers let the LAST matching pattern win, which is what makes
#     `!spikes/tls/*.pem` after `*.pem` mean the same thing in both.
# Two lines are then added that `.gitignore` has no reason to carry: `.git`
# itself, and the one ignored path the Dockerfile copies IN — the debug
# `spike-nat` that nat_rewrite.sh builds on the host. Files under an excluded
# directory can be re-included this way (the context walker descends into a
# directory when an exception pattern lies beneath it), and the exception is
# the only thing that keeps `target/` from being both ignored and needed.
derive_dockerignore() { # derive_dockerignore <path-to-.gitignore>
  local src="$1" line neg pat
  cat <<'EOF'
# GENERATED — do not edit this file. spikes/nat/run.sh derives it from
# .gitignore (every pattern, translated to Docker's matcher) before each
# `docker compose` build, and spikes/nat/local_checks.sh fails when this
# committed copy differs from that derivation. Change .gitignore, or the
# derivation in run.sh; never this.
EOF
  while IFS= read -r line || [ -n "$line" ]; do
    # trailing whitespace, then blank lines and comments
    line="${line%"${line##*[![:space:]]}"}"
    [ -z "$line" ] && continue
    case "$line" in '#'*) continue ;; esac
    neg=""
    case "$line" in '!'*)
      neg='!'
      line=${line#!}
      ;;
    esac
    pat=${line%/}
    pat=${pat#/}
    case "$pat" in
      */*) ;;
      *) pat="**/$pat" ;;
    esac
    printf '%s%s\n' "$neg" "$pat"
  done <"$src"
  cat <<'EOF'
# added by the derivation, not from .gitignore:
.git
# the one ignored path the Dockerfile copies in — the debug spike-nat that
# spikes/nat_rewrite.sh builds on the host before this probe runs. Last match
# wins, so it must follow **/target.
!target/debug/spike-nat
EOF
}
# ── derive_dockerignore end ──────────────────────────────────────────────────

# ── The image runs one platform; the host built the binary for another? ─────
# The Dockerfile copies `target/debug/spike-nat` in and compiles nothing, so
# the binary must be executable on the image's platform. That platform has one
# home, compose.yaml, and is read from there rather than typed here again.
# Refused, not attempted: a binary the image cannot execute fails at `exec`,
# and an exec-format error in the client's log reads exactly like the dial
# failure the naive case is supposed to show.
image_platform=$(sed -n 's/^[[:space:]]*platform:[[:space:]]*\([^[:space:]#]*\).*/\1/p' compose.yaml | sort -u)
platforms=$(printf '%s\n' "$image_platform" | grep -c .)
[ "$platforms" -eq 1 ] ||
  refuse "compose.yaml names $platforms distinct platforms; it must name exactly one, and run.sh reads it from there"
image_arch=${image_platform#linux/}
[ "$image_arch" != "$image_platform" ] ||
  refuse "compose.yaml pins platform '$image_platform', which is not a linux/* platform the copied binary could run on"
host_os=$(uname -s)
case "$(uname -m)" in
  x86_64 | amd64) host_arch=amd64 ;;
  aarch64 | arm64) host_arch=arm64 ;;
  *) host_arch=$(uname -m) ;;
esac
if [ "$host_os" != Linux ] || [ "$host_arch" != "$image_arch" ]; then
  refuse "this host builds spike-nat for $host_os/$host_arch and the image runs $image_platform; the Dockerfile copies the host's binary in rather than compiling, so this probe cannot run from here"
fi

# ── The binary, and where the Dockerfile expects it ─────────────────────────
# `spikes/nat_rewrite.sh` builds it (debug, on the host) before calling this
# script; the Dockerfile copies it from `target/debug/spike-nat` relative to
# the build context, which is the repository root. A `CARGO_TARGET_DIR` that
# moves the build elsewhere leaves nothing at that path — refused with the
# reason, rather than shipping whatever stale binary happens to be there.
bin="$ROOT/target/debug/spike-nat"
if [ -n "${CARGO_TARGET_DIR:-}" ] && [ "$(cd "$CARGO_TARGET_DIR" 2>/dev/null && pwd)" != "$ROOT/target" ]; then
  refuse "CARGO_TARGET_DIR=$CARGO_TARGET_DIR puts spike-nat outside the build context; the Dockerfile copies target/debug/spike-nat"
fi
[ -f "$bin" ] ||
  refuse "no $bin — spikes/nat_rewrite.sh builds it before running this probe (cargo build --bin spike-nat)"
# The file itself, not only the host that built it: an ELF whose e_machine is
# the image's. 0x3e is x86-64 and 0xb7 is AArch64 (ELF spec, e_machine).
case "$image_arch" in
  amd64) want_machine="3e" ;;
  arm64) want_machine="b7" ;;
  *) want_machine="" ;;
esac
magic=$(od -An -tx1 -N4 "$bin" | tr -d ' \n')
machine=$(od -An -tx1 -j18 -N1 "$bin" | tr -d ' \n')
if [ "$magic" != "7f454c46" ] || { [ -n "$want_machine" ] && [ "$machine" != "$want_machine" ]; }; then
  refuse "$bin is not an ELF for $image_platform (magic $magic, e_machine 0x$machine); the image could not execute it"
fi

# ── The context: derived now, so the committed copy cannot drift ────────────
derive_dockerignore "$ROOT/.gitignore" >"$ROOT/.dockerignore" ||
  refuse "could not derive $ROOT/.dockerignore from .gitignore"

reset_shared() {
  rm -rf shared
  mkdir -p shared
}

# Deadline-bounded and sleeping. A loop without a sleep does not wait, which is
# the harness rule that cost this project a debugging cycle in Phase 0.
wait_for_ior() {
  for _ in $(seq 1 120); do
    [ -s shared/server.ior ] && return 0
    sleep 0.5
  done
  return 1
}

run_case() {
  local mode="$1" map="$2" want="$3" label="$4"
  reset_shared
  NAT_MODE="$mode" ORBWEAVER_PUBLISH_MAP="$map" $DC up -d --build server || return 1
  if ! wait_for_ior; then
    # An unmeasured check is a failure, never a pass.
    echo "  FAIL $label: the servant never published a reference"
    $DC logs server | tail -20 | sed 's/^/       /'
    $DC down -v >/dev/null 2>&1
    return 1
  fi
  echo "  ..   $label published: $(head -c 40 shared/server.ior)..."
  NAT_MODE=call $DC run --rm client
  local got=$?
  $DC down -v >/dev/null 2>&1
  if [ "$want" = pass ] && [ "$got" -eq 0 ]; then
    echo "  ok   $label: the client's call completed"
    return 0
  fi
  if [ "$want" = fail ] && [ "$got" -ne 0 ]; then
    echo "  ok   $label: the client could not dial it, as R7 predicts"
    return 0
  fi
  echo "  FAIL $label: wanted the dial to $want, it did not"
  return 1
}

echo "R7 container probe — UNRUN as written; treat a green run with suspicion"
echo "  ..   image $image_platform, host $host_os/$host_arch, binary $bin"

run_case naive "" fail "naive publish (container's own address)" || fails=$((fails + 1))
run_case published '*=host.docker.internal' pass "published (rewritten at publish time)" ||
  fails=$((fails + 1))

echo
if [ "$fails" -eq 0 ]; then
  echo "container probe: PASS"
else
  echo "container probe: FAIL — $fails case(s)"
fi
[ "$fails" -eq 0 ] || exit 1
