//! The plane rule's one home: which operations of the MoE contracts carry a
//! `moe::Tensor` across the wire, and which of those this project serves.
//!
//! `docs/decisions/D006-plane-rule-tensor.md` is the decision and this module
//! is not a second copy of it. D006 settles *what should be true*; this module
//! records **what is measured to be true**, in one place, so the two can be
//! compared by a test instead of by a reader.
//!
//! # Why this module exists at all
//!
//! The plane rule — *the data plane stays out of CORBA; a `Tensor` carries a
//! handle, never a payload* — governs stream F, and until 2026-08-26 it was
//! written in five places and checked in none:
//!
//! 1. a trailing comment on `corpus/golden/22-moe-control-plane.idl:13`
//!    (`// reference-carrying; never inlined`), which binds nothing;
//! 2. `PLAN-MOE` §4.6 and §5, as prose;
//! 3. `docs/decisions/D006-plane-rule-tensor.md`, **APPROVED**, option E:
//!    `Expert::process` and `Router::dispatch` excluded rather than bounded;
//! 4. [`crate::expert_service`]'s module docs, refusing `Router::dispatch`
//!    because serving it *"would commit the project to \[the handle reading\]
//!    silently"*;
//! 5. [`crate::tenant_service`]'s dispatch table, **serving
//!    `moe::Expert::process`** under the comment *"Inherited from
//!    `::moe::Expert`. Served, because inheritance is part of the contract and
//!    a half-served interface is worse than an unserved one."*
//!
//! Four and five are the same crate reaching opposite conclusions about the
//! same operation of the same interface, and nothing was red. That is
//! `CLAUDE.md`'s *where a fact lives* class at full size: a fact with five
//! homes, no owner, and no way to notice that two of them disagree.
//!
//! # The measurement, re-run 2026-08-26
//!
//! D006 rests its recommendation on one falsifiable claim it calls **the
//! consumer census**: *"Enumerate every call site in this repository that
//! requires an activation — not a handle — to cross a process boundary through
//! the ORB. If the count is zero, E is right and A was premature. If it is
//! nonzero, E is wrong today and the recommendation inverts."* D006 recorded
//! the count as zero on 2026-08-14: *"Nothing in the tree serves `process` or
//! `dispatch`, nothing plans to."*
//!
//! **The count is no longer zero.** [`TENSOR_BEARING`] is that census,
//! computed rather than asserted: `tests/one_plane_rule_for_a_tensor.rs`
//! derives the left-hand side by parsing `corpus/golden/22` and
//! `corpus/golden/23` with our own front end, so an operation that starts
//! carrying a `Tensor` cannot join the set without this table moving.
//!
//! Five operations in those two contracts carry a `Tensor` across the wire.
//! **Four are served. One is refused**, and its recorded ground applies to the
//! other four as well — with full force to the two that carry an `Activation`
//! in *both* directions.
//!
//! # This is a rule-level conflict, not a slip
//!
//! Nobody was careless. **`PLAN-SERVICES` §1 rule 2 made the tenant servant
//! right**: *"Only the subset a named consumer needs. Every operation
//! implemented must name who calls it… Omitted operations are refused loudly,
//! never half-served."* `moe::Expert::process` has a named consumer —
//! `spikes/f5_peer_client.py` — and F5's goal was every declared operation of
//! `corpus/golden/23` answering. Serving it was that rule applied correctly.
//!
//! `PLAN-MOE` §3's plane rule and D006 option E say the same operation must
//! not be served at all. **Two project rules point opposite ways at one
//! operation, and no document mentions the other.** That is the finding, and
//! resolving it is a decision rather than a batch: it constrains what a
//! deployment may put in a `Tensor`, which §5.3 says is not settled by
//! whoever commits first.
//!
//! It was never hidden. Four documents state both halves:
//!
//! | document | says the operation is excluded | says it is served |
//! |---|---|---|
//! | `docs/decisions/D006` | option E, APPROVED 2026-08-14 | approval block: *"Nothing serves them, nothing plans to"* — false since |
//! | `PLAN-SERVICES` §8.1.1 | `Router::dispatch`'s exclusion, D006 | four sentences later: *"the experts themselves are served elsewhere — `corpus/golden/23`'s `EnterpriseExpert` and the shared `::moe::Expert` both answer"* |
//! | `SERVICES-COVERAGE` | §6 table: `process` **absent**, `BAD_OPERATION` | §7 table: `process` **served**, on the expert and on the shared base |
//! | this crate | [`crate::expert_service`], twice | [`crate::tenant_service`], twice |
//!
//! `PLAN-SERVICES` §8.1.1 holds both halves *in one paragraph*, in the
//! document whose entire subject is refusals that carry a reason.
//! `SERVICES-COVERAGE` is generated by a script, so it was never going to
//! notice that two of its own tables disagree about one operation of one
//! interface.
//!
//! # What re-running the census takes
//!
//! `cargo test -p orbweaver-object --test one_plane_rule_for_a_tensor`. It
//! parses the contracts, so it needs no fixture, no omniORB and no network for
//! the census half; the status half stands two servants up on loopback.
//! D006's measurement 1 was *"cheap… it can be run now, by reading, and it
//! should be run before this document is approved"* — it was run once, on the
//! day of approval, and the inversion clause it carried was never checked
//! again. **A measurement with a stated inversion condition, taken once and
//! never re-taken, is `CLAUDE.md`'s floor-quoted-as-a-figure class with higher
//! stakes**: the figure did not merely drift upward in silence, it crossed the
//! threshold its own author wrote down.
//!
//! # Why both readings condemn the four, and this is the sharpened reason
//!
//! D006 §1 (P3) established that no predicate over a contract distinguishes a
//! handle from a payload, so "is this a payload?" is not a question the
//! contract can answer. It does not have to be asked here, because the three
//! echoing operations are condemned under *either* reading:
//!
//! - `ComposedModel::infer` ends at `Ok(x)`, and both `Expert::process` arms
//!   end at `x.write_to(out)`. Each reads an unbounded `sequence<octet>` off
//!   the wire and writes the same bytes back without interpreting one of them.
//! - Under the **payload** reading, an operation whose job is to move an
//!   unbounded octet sequence between two processes is the data plane, which
//!   §3 puts permanently out of CORBA.
//! - Under the **handle** reading, the servant is handed a handle it never
//!   dereferences and returns it unchanged, so the operation performs no work
//!   at all — it is a transport for the bytes and nothing else.
//!
//! There is no third reading under which an unread echo of an unbounded octet
//! sequence is a control-plane operation. This is what the refusal in
//! [`crate::expert_service`] should say and did not: the sentence *"serving it
//! would commit the project silently"* describes a commitment that **has
//! already been made**, four times, by the neighbouring servant, under a green
//! harness — `spikes/run_checks.sh` runs `spikes/f5_peer_client.py`, which has
//! an omniORB peer send a real `Activation` to `process` and asserts *"every
//! declared operation was called by the peer"*. The harness does not merely
//! permit the breach; it gates that it stays.
//!
//! # What this module does not do
//!
//! It does not change what is served. Serving `dispatch` would add a fifth
//! crossing and closing the other four is a contract change (a new version of
//! `Expert` and `ComposedModel` without them, which is §5.3's path and D006
//! option E's stated cost), with live consumers in `spikes/f5_peer_client.py`
//! and `spike-tenants`. Both are separate batches. What this module does is
//! make the divergence **impossible to hold without noticing** — which is the
//! step D006 §6 says the project has never actually taken for this rule:
//! *"E is recommended not because it enforces the rule but because it is the
//! only option that removes the opportunity instead of labelling it."* The
//! opportunity was never removed. Nothing removed anything.

use std::fmt;

/// Whether this project answers an operation that carries a `Tensor`.
///
/// The distinction is on the wire and not only in this table: a refused
/// operation answers `NO_IMPLEMENT` — *the contract declares it and this
/// servant has decided not to implement it* — and never `BAD_OPERATION`,
/// which is what an oversight says.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PlaneStatus {
    /// A caller reaches it and gets an answer.
    Served,
    /// A caller reaches it and gets `NO_IMPLEMENT`.
    Refused,
}

impl fmt::Display for PlaneStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            PlaneStatus::Served => "served",
            PlaneStatus::Refused => "refused",
        })
    }
}

/// One operation of the MoE contracts whose signature carries a
/// `moe::Tensor`, and what this project does about it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TensorBearing {
    /// The repository id of the interface that **declares** it. An inherited
    /// operation is listed once, under its declaring interface, which is where
    /// the contract puts it.
    pub interface: &'static str,
    /// The operation name as it appears on the wire.
    pub operation: &'static str,
    /// Which direction the `Tensor` travels.
    pub direction: Direction,
    /// What this project does.
    pub status: PlaneStatus,
    /// Why — never empty, and checked to be non-empty, because an entry
    /// without a reason is the state this module exists to end.
    pub why: &'static str,
}

/// Which way a `Tensor` crosses.
///
/// Recorded because D006 leaned on it once and was corrected by its own
/// finding: §4.6 filed `select` as pure control plane on the strength of its
/// *return* being references-only, and then found a `Tensor` on its input
/// side. Direction is a real distinction and it is not the same as safety.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    /// The caller sends one.
    In,
    /// The servant returns one.
    Out,
    /// Both, which is the shape D006 option E named.
    InOut,
}

impl fmt::Display for Direction {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Direction::In => "in",
            Direction::Out => "out",
            Direction::InOut => "in and out",
        })
    }
}

/// The consumer census D006 asked for, kept where a test can check it.
///
/// The **membership** of this table is not a judgement: it is derived from the
/// two contracts by `tests/one_plane_rule_for_a_tensor.rs`, which parses them
/// and computes every operation whose return or parameters reach
/// `moe::Tensor` through any typedef or struct. Only [`TensorBearing::status`]
/// and [`TensorBearing::why`] are written by hand, and the status is checked
/// against the servants' own answers over a socket.
pub const TENSOR_BEARING: &[TensorBearing] = &[
    TensorBearing {
        interface: "IDL:moe/Expert:1.0",
        operation: "process",
        direction: Direction::InOut,
        status: PlaneStatus::Served,
        why: "D006 option E excluded it. It is served anyway, in two arms of \
              tenant_service (Kind::Expert and Kind::Base), each ending at \
              `x.write_to(out)` — the caller's octet sequence echoed back \
              unread. An omniORB peer calls it under the harness \
              (spikes/f5_peer_client.py), so this is a live consumer and \
              removing it is a §5.3 version change, not a deletion.",
    },
    TensorBearing {
        interface: "IDL:moe/Router:1.0",
        operation: "select",
        direction: Direction::In,
        status: PlaneStatus::Served,
        why: "The `Tensor` is `GateSignal::affinity`, on the input side only. \
              D006 left `select` open and corrected PLAN-MOE §4.6 for having \
              called it free of the plane question. The affinity blob is \
              decoded and never read, which `the_affinity_tensor_is_not_read` \
              pins as a property rather than a promise.",
    },
    TensorBearing {
        interface: "IDL:moe/Router:1.0",
        operation: "dispatch",
        direction: Direction::InOut,
        status: PlaneStatus::Refused,
        why: "The one refusal. D006 option E, and the only entry in this table \
              whose recorded ground is also its behaviour. Its ground applies \
              verbatim to `process` and `infer`, which are served.",
    },
    TensorBearing {
        interface: "IDL:moe/enterprise/EnterpriseExpert:1.0",
        operation: "adapter_delta",
        direction: Direction::Out,
        status: PlaneStatus::Served,
        why: "Returns a bare `::moe::Tensor` — the tenant's stored adapter \
              bytes, which the servant owns rather than echoes. This is the \
              clearest payload crossing of the five: an adapter delta is model \
              weights, and no handle reading of it was ever proposed.",
    },
    TensorBearing {
        interface: "IDL:moe/enterprise/ComposedModel:1.0",
        operation: "infer",
        direction: Direction::InOut,
        status: PlaneStatus::Served,
        why: "`::moe::Activation infer(in ::moe::Activation x, ...)`, ending at \
              `Ok(x)`. Same shape as `process` and same standing: a live peer \
              consumer, so the exit is a contract version rather than an edit.",
    },
];

/// The four crossings that are served, which is the count D006's census
/// predicted would be zero.
///
/// A `usize` and not a literal in prose: `CLAUDE.md`'s *a floor is not a
/// figure* rule applies to counts in either direction, and this one is the
/// measurement rather than a floor.
#[must_use]
pub fn served_crossings() -> usize {
    TENSOR_BEARING.iter().filter(|t| t.status == PlaneStatus::Served).count()
}

/// Look one operation up by the pair that identifies it on the wire.
#[must_use]
pub fn status_of(interface: &str, operation: &str) -> Option<PlaneStatus> {
    TENSOR_BEARING
        .iter()
        .find(|t| t.interface == interface && t.operation == operation)
        .map(|t| t.status)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every entry carries a reason. An entry without one is the state this
    /// module exists to end, so it is checked rather than trusted.
    #[test]
    fn every_crossing_records_why() {
        for t in TENSOR_BEARING {
            assert!(
                t.why.len() > 40,
                "{}::{} has no usable reason — an entry without one is the \
                 five-homes state this module replaced",
                t.interface,
                t.operation
            );
        }
    }

    /// The census is not zero, and saying so is the whole finding. If this
    /// ever goes to zero the exit was a contract version and D006 needs
    /// amending in the other direction.
    #[test]
    fn the_consumer_census_is_not_zero() {
        assert_eq!(
            served_crossings(),
            4,
            "D006's census claimed zero on 2026-08-14 and the recommendation \
             inverts if it is nonzero; re-measured 2026-08-26"
        );
        assert_eq!(status_of("IDL:moe/Router:1.0", "dispatch"), Some(PlaneStatus::Refused));
    }
}
